### ISSUE TITLE
Failed building in MSVS2015

### ISSUE THREAD

**Issue by CAIQT** [microsoftarchive/redis#409] opened 2016-02-15 10:04 UTC
After upgrading the project files to vs2015, it produces many building errors (and even error dialog says that "Microsoft C/C++ Optimizing Compiler has stopped working" when compling).

Severity    Code    Description Project File    Line    Suppression State
Error   C1189   #error:  Macro definition of snprintf conflicts with Standard Library function declaration  lua c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h    1927  
Error   C2061   syntax error: identifier 'gettimeofdaysecs' Win32_Interop   e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   34  
Error   C2059   syntax error: ';'   Win32_Interop   e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   34  
Error   C2059   syntax error: '<parameter-list>'    Win32_Interop   e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   34  
Error   C2143   syntax error: missing ')' before '_'    Win32_Interop   e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   36  
Error   C2143   syntax error: missing '{' before '_'    Win32_Interop   e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   36  
Error   C2059   syntax error: 'type'    Win32_Interop   e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   36  
Error   C2059   syntax error: ')'   Win32_Interop   e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   36  
Error   C2365   'clock': redefinition; previous definition was 'data variable'  Win32_Interop   c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\time.h 137 
Error   C1903   unable to recover from previous error(s); stopping compilation  Win32_Interop   c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\time.h 137 
Error   C2371   'int_fast16_t': redefinition; different basic types RedisServer C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h 36  
Error   C2371   'uint_fast16_t': redefinition; different basic types    RedisServer C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h 40  
Error   C2365   'fdapi_fstat64': redefinition; previous definition was 'data variable'  RedisServer C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\sys\stat.h 237 
Error   C2061   syntax error: identifier 'gettimeofdaysecs' RedisServer e:\tmp\redis-3.0\redis-3.0\src\Win32_Interop\Win32_Time.h   34  
Error   C2059   syntax error: ';'   RedisServer e:\tmp\redis-3.0\redis-3.0\src\Win32_Interop\Win32_Time.h   34  
Error   C2059   syntax error: '<parameter-list>'    RedisServer e:\tmp\redis-3.0\redis-3.0\src\Win32_Interop\Win32_Time.h   34  
Error   C2143   syntax error: missing ')' before '_'    RedisServer e:\tmp\redis-3.0\redis-3.0\src\Win32_Interop\Win32_Time.h   36  
Error   C2143   syntax error: missing '{' before '_'    RedisServer e:\tmp\redis-3.0\redis-3.0\src\Win32_Interop\Win32_Time.h   36  
Error   C2059   syntax error: 'type'    RedisServer e:\tmp\redis-3.0\redis-3.0\src\Win32_Interop\Win32_Time.h   36  
Error   C2059   syntax error: ')'   RedisServer e:\tmp\redis-3.0\redis-3.0\src\Win32_Interop\Win32_Time.h   36  
Error   C2365   'clock': redefinition; previous definition was 'data variable'  RedisServer C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h 137 
Error   C1903   unable to recover from previous error(s); stopping compilation  RedisServer C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\time.h 137 
Error   C2061   syntax error: identifier 'gettimeofdaysecs' RedisCli    e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   34  
Error   C2059   syntax error: ';'   RedisCli    e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   34  
Error   C2059   syntax error: '<parameter-list>'    RedisCli    e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   34  
Error   C2143   syntax error: missing ')' before '_'    RedisCli    e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   36  
Error   C2143   syntax error: missing '{' before '_'    RedisCli    e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   36  
Error   C2059   syntax error: 'type'    RedisCli    e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   36  
Error   C2059   syntax error: ')'   RedisCli    e:\tmp\redis-3.0\redis-3.0\src\win32_interop\win32_time.h   36  
Error   C2365   'clock': redefinition; previous definition was 'data variable'  RedisCli    c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\time.h 137 
Error   C1903   unable to recover from previous error(s); stopping compilation  RedisCli    c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\time.h 137 
Error   LNK1181 cannot open input file 'E:\tmp\redis-3.0\redis-3.0\msvs\x64\Debug\Win32_Interop.lib'    RedisCheckDump  E:\tmp\redis-3.0\redis-3.0\msvs\RedisCheckDump\LINK 1  
Error   LNK1181 cannot open input file 'E:\tmp\redis-3.0\redis-3.0\msvs\x64\Debug\Win32_Interop.lib'    RedisCheckAof   E:\tmp\redis-3.0\redis-3.0\msvs\RedisCheckAof\LINK  1  
Error   C2365   'fdapi_fstat64': redefinition; previous definition was 'data variable'  RedisBenchmark  c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\sys\stat.h 237

**Comment by enricogior** [comment] 2016-02-15 10:08
Hi @CAIQT 
VS 2015 is not supported yet.
Thank you.

Closing this as a duplicate of https://github.com/MSOpenTech/redis/issues/382

**Closed as completed by enricogior** 2016-02-15 10:08 UTC
