### ISSUE TITLE
Redis 2103 build crash

### ISSUE THREAD

**Issue by chester89** [microsoftarchive/redis#355] opened 2015-11-10 20:52 UTC
Just received this error from my test Redis server

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[3604] # --- ABORT
[3604] # --- STACK TRACE
redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:95)(0x00000016, 0x40150880, 0x00000000, 0x00000001)
redis-server.exe!AbortHandler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:206)(0x00000016, 0xB20E61EF, 0x000000D4, 0x776D8FDA)
redis-server.exe!raise(f:\dd\vctools\crt\crtw32\misc\winsig.c:587)(0x00000001, 0x00000000, 0x00000050, 0x00000041)
redis-server.exe!abort(f:\dd\vctools\crt\crtw32\misc\abort.c:82)(0xF418C250, 0x4009610E, 0x0000005E, 0x0000005E)
redis-server.exe!dlmalloc(c:\release\redis\src\win32_interop\win32_dlmalloc.c:4638)(0x00000041, 0x00000068, 0xF403EC68, 0x0012F5F0)
redis-server.exe!zmalloc(c:\release\redis\src\zmalloc.c:143)(0x00001B86, 0x0012F461, 0x00000000, 0x0012F461)
redis-server.exe!rdbSaveLzfStringObject(c:\release\redis\src\rdb.c:229)(0x00001B86, 0xF406FE68, 0x000000C3, 0xF40F63C8)
redis-server.exe!rdbSaveRawString(c:\release\redis\src\rdb.c:295)(0x0012F5F0, 0x00001B86, 0xF4187D41, 0x00000000)
redis-server.exe!rdbSaveObject(c:\release\redis\src\rdb.c:544)(0x0012F5F0, 0x00000000, 0xF401EBA0, 0xF401EBA0)
redis-server.exe!rdbSaveRio(c:\release\redis\src\rdb.c:692)(0x40133210, 0x034A0000, 0x00000000, 0x044A275C)
redis-server.exe!rdbSave(c:\release\redis\src\rdb.c:760)(0x0C000000, 0x5647C48D, 0x034A0000, 0x00000088)
redis-server.exe!QForkChildInit(c:\release\redis\src\win32_interop\win32_qfork.cpp:308)(0xFFFFFFFF, 0x00000000, 0xFFFFFFFF, 0x00000005)
redis-server.exe!QForkStartup(c:\release\redis\src\win32_interop\win32_qfork.cpp:758)(0x00000006, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1368)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!__tmainCRTStartup(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
kernel32.dll!BaseThreadInitThunk(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[3604] # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

I can post my config if it helps

**Comment by enricogior** [comment] 2015-11-16 16:30
Hi @chester89 
how long has the server been running before the crashed occurred? 
The crash is caused by a memory allocation failure that in turn may be caused by the memory heap fragmentation.
We have fixed the problem in v3.0 and in the future we may bring the fix to 2.8 but it's a high impact change and it won't happen anytime soon.
You may workaround the problem by restarting the service after a certain amount of time in order to reset the memory heap fragmentation.
The amount of time before restarting the service depends on the server usage.
The INFO command may give insights on the memory usage to determine when it's better to restart the service.

**Comment by chester89** [comment] 2015-11-17 10:07
The thing is, I also run 2103 build in production and it's completely fine.
This particular instance was running for little more than 5 hours before it
crashed.

2015-11-16 19:30 GMT+03:00 Enrico Giordani notifications@github.com:

> Hi @chester89 https://github.com/chester89
> how long has the server been running before the crashed occurred?
> The crash is caused by a memory allocation failure that in turn may be
> caused by the memory heap fragmentation.
> We have fixed the problem in v3.0 and in the future we may bring the fix
> to 2.8 but it's a high impact change and it won't happen anytime soon.
> You may workaround the problem by restarting the service after a certain
> amount of time in order to reset the memory heap fragmentation.
> The amount of time before restarting the service depends on the server
> usage.
> The INFO command may give insights on the memory usage to determine when
> it's better to restart the service.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/355#issuecomment-157088864.

## 

Yours faithfully,
Gleb

**Comment by enricogior** [comment] 2015-11-17 15:16
@chester89 
do the test server and the production server use the same configuration?

**Comment by chester89** [comment] 2015-11-19 11:37
​They're nearly identical, test server may write to RDB on wider intervals.​

2015-11-17 18:16 GMT+03:00 Enrico Giordani notifications@github.com:

> @chester89 https://github.com/chester89
> do the test server and the production server use the same configuration?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/355#issuecomment-157399679.

## 

Yours faithfully,
Gleb

**Comment by enricogior** [comment] 2016-06-21 09:28
@chester89 
the bug report is consistent with a bug that has been fixed in [2.8.2401](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2401).

**Closed as completed by enricogior** 2016-06-21 09:28 UTC

**Comment by chester89** [comment] 2016-06-21 09:36
I see, will try the new build shortly, thanks

2016-06-21 12:28 GMT+03:00 Enrico Giordani notifications@github.com:

> Closed #355 https://github.com/MSOpenTech/redis/issues/355.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/MSOpenTech/redis/issues/355#event-698778195, or mute
> the thread
> https://github.com/notifications/unsubscribe/AALnfApqrLO7Gj_gq4gqE2RqpyhYBWEpks5qN66lgaJpZM4GfwpJ
> .

## 

Yours faithfully,
Gleb

**Comment by enricogior** [comment] 2016-06-21 12:41
@chester89 
update: the latest release is [2.8.2402](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2402).
Sorry about the double release in one day.
Thank you.
