### ISSUE TITLE
..\src\db.c:776 'dictFind(db->dict,key->ptr) != NULL' is not true Assertion thrown

### ISSUE THREAD

**Issue by Psigio** [microsoftarchive/redis#178] opened 2014-10-15 10:40 UTC
Hi,

We received the following Assertion Failed error on Redis 2.8.14 on Windows Server 2008 R2:

```
[6724] 14 Oct 14:56:43.077 * 10 changes in 300 seconds. Saving...
[6724] 14 Oct 15:12:12.964 # fork operation complete
[6724] 14 Oct 15:12:31.347 * Background saving terminated with success
[6724] 14 Oct 15:12:31.561 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[6724] 14 Oct 15:12:31.561 # === ASSERTION FAILED OBJECT CONTEXT ===
[6724] 14 Oct 15:12:31.562 # Object type: 0
[6724] 14 Oct 15:12:31.562 # Object encoding: 0
[6724] 14 Oct 15:12:31.562 # Object refcount: 1
[6724] 14 Oct 15:12:31.562 # Object raw string len: zu
[6724] 14 Oct 15:12:31.562 # Object raw string content: << Removed - 102 character long string >>
[6724] 14 Oct 15:12:31.562 # === ASSERTION FAILED ===
[6724] 14 Oct 15:12:31.562 # ==> ..\src\db.c:776 'dictFind(db->dict,key->ptr) != NULL' is not true
```

Is this an issue in the code?

Thanks!

**Comment by jepickett** [comment] 2014-10-20 21:46
Are you able to reproduce this problem? I have not seen this before.

**Comment by Psigio** [comment] 2014-10-21 09:24
Hi - unfortunately not - it's only occurred once on one of our servers and it's not clear what the circumstances were that caused it.  The "raw string content" mentioned in the report is a key which had a ten minute TTL on it and I think that the error was thrown at the point the TTL expired.

**Comment by jepickett** [comment] 2014-11-14 19:35
Closing this as a likely duplicate of 185.

**Closed as completed by jepickett** 2014-11-14 19:35 UTC
