### ISSUE TITLE
150GB in RedisQFork_####.dat files

### ISSUE THREAD

**Issue by PaulBGD** [microsoftarchive/redis#283] opened 2015-07-31 19:35 UTC
I found several files in C:\Windows\ServicesProfiles\NetworkService\AppData\Local\Redis that add up to nearly 150GB. 

For some reason, them being in this folder means that Explorer and other programs cannot find them without being ran as administrator. 

Is there any reason for all of these files? I didn't even have any data in my redis.

**Comment by enricogior** [comment] 2015-07-31 19:40
Hi @PaulBGD,
do you still have the list of the files?

**Comment by PaulBGD** [comment] 2015-07-31 19:50
Sorry I don't, I had less than a GB left and I needed the space.

**Comment by enricogior** [comment] 2015-07-31 19:52
@PaulBGD can you at least tell me what name/file extension they had?

**Comment by mehdyh** [comment] 2015-07-31 19:54
I've also have a huge file named _RedisQFork_2568.dat_ over there. can we
delete it safely?

Thanks,

Mehdy Haghy
Chief Technology Officer
Intellirose LLC
Cell: (312)914-7211 <%28562%29552-5460>
Phone: (866) 386-2444

**Comment by enricogior** [comment] 2015-07-31 19:56
@mehdymohajery
that is the the memory mapped filed used by Redis on Windows, if Redis is running it can't be deleted.

**Comment by PaulBGD** [comment] 2015-07-31 19:58
@enricogior As I said in the title, they all looked like `RedisQFork_####.dat` where each # was a digit.

**Comment by enricogior** [comment] 2015-07-31 20:13
@PaulBGD sorry... it's 10PM here and I guess I'm getting tired ;)
The .dat files are used for the memory map mechanism, the expected behavior is that one single .dat file is created when redis-server.exe starts and the file is supposed to be deleted when redis-server.exe exits.
If multiple instances of redis-server.exe are running at the same time, multiple .dat files are created.
You can change the default location of the .dat file editing the redis configuration file and setting the `heapdir` flag for example `heapdir c:\redis-heap`

**Comment by starrychloe** [comment] 2015-09-02 02:43
Found a 32GB file. Why not save in the temp directory by default?

**Comment by enricogior** [comment] 2015-09-02 07:43
Hi @starrychloe,
I honestly don't know the reason behind that initial choice, but your suggestion seems reasonable.
Thank you.

**Comment by PaulBGD** [comment] 2015-09-02 18:20
Should I close this? Since I deleted the files and can't reproduce it on the latest version, the issue seems meaningless.

**Comment by enricogior** [comment] 2015-09-02 18:28
@PaulBGD,
sure, feel free to close it.
Thank you.

**Closed as completed** 2015-09-02 18:33 UTC

**Comment by Hallmanac** [comment] 2015-10-02 15:18
Just a heads up, this happened to me yesterday (2015-10-01). Very random. I am not able to reproduce it either. Perhaps something to be aware of for the team?
