### ISSUE TITLE
MSI installation fails

### ISSUE THREAD

**Issue by traxswe** [microsoftarchive/redis#276] opened 2015-07-29 09:22 UTC
The MSI installation fails for 2.8.2101 when it tries to start the service. It should have sufficient permissions since we are installing it from an admin account.

**Comment by enricogior** [comment] 2015-07-29 12:16
Hi @traxswe,
can you please provide more information regarding the error?
Does the error occurs before the MSI finishes or does it occur after the installation is completed?
If you reboot the machine the service still fails to start?
If you try to start Redis from a command prompt window does it fail?
Thank you.

**Comment by traxswe** [comment] 2015-07-29 16:52
Hi @enricogior!
Sorry, i should have supplied you with more to begin with. See the attached images.

1) The error occurs before it finishes the installation. It stops and fails when it tries to start the service.
2) The machine has been rebooted and it still stops at the start of the service.
3) Downloading the binaries and running redis-server.exe work.

![reddis1](https://cloud.githubusercontent.com/assets/2046175/8963871/a8000838-3622-11e5-9430-788ccd7fd7ce.PNG)
![reddis2](https://cloud.githubusercontent.com/assets/2046175/8963872/a800c1b0-3622-11e5-9ddb-6d88fbc7137e.PNG)

**Comment by prjm** [comment] 2015-07-30 06:55
Apparently same problem here.

The windows event log says that the redis service is dependent on the netlogon sevice, which could not started. The netlogon service says, it could not start because the computer is not part of a domain (which is true).

Can I (somehow) remove the dependency to the netlogon service?

**Comment by enricogior** [comment] 2015-07-30 11:33
Hi @traxswe,
what Windows version are you running? (I tried on Windows 7 and Windows Server 2012 R2 but I couldn't repro the problem).
Can you please try to uninstall Redis first and then reinstall it?
What was the Redis version that you successfully installed before trying v2.8.2101?
Thank you.

**Comment by enricogior** [comment] 2015-07-30 11:36
Hi @prjm,
I just verified on a Windows Server 2012 R2 that the Redis installer works as expected when the netlogon service is stopped. What Windows version are you using? 
Thank you.

**Comment by chester89** [comment] 2015-07-30 12:47
@enricogior I can try installing on Win Server 2008 R2 today

**Comment by enricogior** [comment] 2015-07-30 13:04
Hi @chester89, 
thanks for helping :)

**Comment by chester89** [comment] 2015-07-30 15:27
@enricogior I just tried to reproduce it on Windows Server 2008 R2 - no luck. I can both start server from console and install it from msi - service starts, and I can talk to it using console client

**Comment by enricogior** [comment] 2015-07-30 15:29
@chester89 thank you!

**Comment by enricogior** [comment] 2015-07-30 16:55
@osherdo,
did you have an exiting Redis installation when you tried to install the latest MSI?

**Comment by enricogior** [comment] 2015-07-30 17:04
@traxswe, @prjm, @osherdo,
can you please open a command prompt window, navigate where the Redis MSI is located and run:
    `msiexec /i Redis-x64-2.8.2101.msi /l*v msi.log`
Please send the msi.log file to winredis-bugs@microsoft.com
Thank you.

**Comment by osherdo** [comment] 2015-07-30 17:05
I actually did. 2.4.6 is the version I had and worked well.

i will do that and send you immediately.

**Comment by enricogior** [comment] 2015-07-30 17:10
@osherdo,
can you also uninstall the 2.4.6 version first and then install the new one?
Thank you.

**Comment by osherdo** [comment] 2015-07-30 17:13
Did that. still have the problem coming. Just sent you the log file as you requested.

**Comment by enricogior** [comment] 2015-07-30 17:35
@osherdo, I received the log file, thank you.
Can you please try to run redis-server.exe manually?
Open a command prompt windows, navigate to the redis folder `cd "\Program Files\Redis"` and run
`redis-server.exe`, does it fail?

**Comment by osherdo** [comment] 2015-07-30 17:44
@enricogior thanks. Did what you asked for.

This is the output I get:

```
C:\Program Files\Redis>redis-server.exe
[5052] 28 Jul 09:24:15.620 #
The Windows version of Redis allocates a large memory mapped file for sharing
the heap with the forked process used in persistence operations. This file
will be created in the current working directory or the directory specified by
the 'heapdir' directive in the .conf file. Windows is reporting that there is
insufficient disk space available for this file (Windows error 0x70).

You may fix this problem by either reducing the size of the Redis heap with
the --maxheap flag, or by moving the heap file to a local drive with sufficient
space.
Please see the documentation included with the binary distributions for more
details on the --maxheap and --heapdir flags.

Redis can not continue. Exiting.
```

I've done that while stuck on the installation of Redis 2.8

**Comment by enricogior** [comment] 2015-07-30 17:48
@osherdo,
please take the time to read the [Memory Configuration wiki](https://github.com/MSOpenTech/redis/wiki/Memory-Configuration) it explains the configuration requirements to run Redis.
If you have any question please let me know.

**Comment by osherdo** [comment] 2015-07-30 18:27
@enricogior I read it. I just don't know where I am configuring the maxmemory and maxheap for redis.

**Comment by enricogior** [comment] 2015-07-30 18:53
@osherdo,
when running redis as a service you need to edit the c:\program files\redis\redis.windows-service.conf configuration file.

**Comment by osherdo** [comment] 2015-07-30 19:00
@enricogior thanks for that, will do.

By the way , is this the same place to change port for Redis?

**Comment by osherdo** [comment] 2015-07-30 19:06
nvm, I find that changing the port is indeed in the same file. thanks for supporting me.

**Comment by enricogior** [comment] 2015-07-30 19:13
@osherdo,
my pleasure ;)

**Comment by traxswe** [comment] 2015-07-31 15:39
@enricogior 
"what Windows version are you running? (I tried on Windows 7 and Windows Server 2012 R2 but I couldn't repro the problem).
Can you please try to uninstall Redis first and then reinstall it?
What was the Redis version that you successfully installed before trying v2.8.2101?
Thank you."

Windows 8.1 and i could also not find any other errors in the event log to pin point the problem. Just the picture above.
The only version i have now of Redis is the exe-files, nothing installed. This is also the first version i download so there is nothing to uninstall.

**Comment by osherdo** [comment] 2015-08-01 01:10
i Believe the error is happening since there is less than 1GB avalable on my virtual machine. 

I tested Redis 2.8 on my windows 8.1 system and it works just great. 

I tried to reduce the maxheap to 1000 (just for instace to see what's going on) and it still shows the same error. I think moving my dev environment outside of virtual system would be the best solution for this.

**Comment by enricogior** [comment] 2015-08-01 06:36
@traxswe 
the problem seems to be not enough disk space or not enough system paging file size, I'm working on a fix that adds a step during setup to set a lower maxheap value to avoid the problem.

**Comment by enricogior** [comment] 2015-08-01 06:41
@osherdo 
`maxheap 1000` is too low, try `maxheap 150MB` and `maxmemory 100MB`.

**Comment by osherdo** [comment] 2015-08-02 02:23
Will test it soon @enricogior . Meanwhile I am setting my environement in Windows 8.1. Will update in this post.

**Comment by thomasbrueggemann** [comment] 2015-08-25 14:44
We essentially encounter the same problem as @traxswe and @prjm reported with the 2.8.2101 and 2.8.2102 MSIs.
The service won't start because of the dependency to the netlogon service which won't start because the server is not part of a domain.

No previous versions were installed.

Anybody found a solution to this yet?

**Comment by enricogior** [comment] 2015-08-25 15:07
Hi @thomasbrueggemann,
the error is misleading, there isn't any dependency to the netlogon service and being part of a domain is not required.
The problem is related to the memory/disk space [requirements](https://github.com/MSOpenTech/redis/wiki/Memory-Configuration), so please check the amount of available disk space and the size of the system paging file.

The fix for this problem will very likely be included in the next release.
Raising the priority to P1.

**Comment by thomasbrueggemann** [comment] 2015-09-01 21:32
While this did not help with the MSI installation, I copied the C:\Program Files\Redis directory to a safe place, let the MSI fail and pasted the Redis directory where I needed it to be.
Installing via command line `redis-server --service-install redis.windows.conf` worked perfectly well.

I adjusted the memory/disk space requirements as you pointed out. Thank you!

**Comment by enricogior** [comment] 2015-09-08 14:21
The new [release 2.8.2103](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2103) contains the fix for this issue.
The MSI now let set the `maxmemory` and `maxheap` values.
If redis-server.exe fails to start, the error is reported to the Event Log.
Thank you.

**Closed as completed by enricogior** 2015-09-08 14:21 UTC
Labels: Bug, P1, Solved

**Comment by osherdo** [comment] 2015-09-08 14:26
good to hear @enricogior ,surely could help some users. (My problem with it was when I installed Redis on virtualbox virtual machine).

**Comment by tschiela** [comment] 2015-11-04 21:02
@thomasbrueggemann the only solution that worked for me. Thank you
