### ISSUE TITLE
redis 2.8.2102 crash during start

### ISSUE THREAD

**Issue by ka3a4ok** [microsoftarchive/redis#304] opened 2015-08-28 07:55 UTC
Redis 2.8.2102 crash during start wo any crash report in console. Redis 2.8.2101 starts properly.

Windows 7, 64 bit

**Comment by enricogior** [comment] 2015-08-28 08:27
Hi @ka3a4ok,
please follow the instruction on how to obtain a mini dump crash:
https://github.com/MSOpenTech/redis/wiki/Mini-Dump-Configuration-Instructions
Also provide the configuration file and the log.
Thank you.

**Comment by ka3a4ok** [comment] 2015-08-28 12:55
configuration file - default

**Comment by enricogior** [comment] 2015-08-28 12:58
@ka3a4ok,
do you start Redis as a Windows Service or do you run `redis-server.exe` from the console?

**Comment by ka3a4ok** [comment] 2015-08-28 13:25
I start redis-server.exe from the console. It's show message about using default config and then fails. When there is another version redis-server running, then it starts and close without crash, because port conflict. Windows 7 SP1 is with cyrilic localization . I tried to run redis on different PC. The results is same - crash.

**Comment by enricogior** [comment] 2015-08-28 13:39
@ka3a4ok,
I need a crash report, without I can't help, please read:
https://github.com/MSOpenTech/redis/wiki/Mini-Dump-Configuration-Instructions
Thank you.

**Comment by ka3a4ok** [comment] 2015-08-29 11:21
![default](https://cloud.githubusercontent.com/assets/890755/9561696/3fe2b760-4e59-11e5-8c61-f1bc86b34aed.png)

**Comment by enricogior** [comment] 2015-08-29 11:46
@ka3a4ok,
thanks for posting the call stack.
The crash happens while releasing some memory after Redis failed to start listening on the 6379 port (if you are using the default value).
I'll fix the bug that causes the crash, but that won't fix the problem you are having.
For some reason that is specific of your setup, Redis fails to bind to the listening port.
Try using a different port, for example 6380 or 20000 or 30000.
Thank you.

**Comment by ka3a4ok** [comment] 2015-08-29 12:01
Previous version successfull starts with default port on same machine.

**Comment by enricogior** [comment] 2015-08-29 12:07
@ka3a4ok,
the failure happens in FDAPI_AcceptEx, try to step through the debugger in Win32_FDAPI.cpp starting at line 159:
        SOCKET sListen = RFDMap::getInstance().lookupSocket(listenRFD);
to see were it fails.
Thank you.

**Comment by ka3a4ok** [comment] 2015-08-29 12:22
There is LastError = 0x00002726:"An invalid argument" after acceptex on line 178 call.

**Comment by enricogior** [comment] 2015-08-29 12:31
@ka3a4ok 
can you take a screenshot of the local variables just before the acceptex call?
It should look like this:
![locals](https://cloud.githubusercontent.com/assets/3206696/9561900/8bb192d2-4e5a-11e5-8d5d-d215b6713215.png)

**Comment by ka3a4ok** [comment] 2015-08-29 12:37
![default](https://cloud.githubusercontent.com/assets/890755/9561922/dd6a1e74-4e63-11e5-9810-4cd68b1a6a40.png)

**Comment by enricogior** [comment] 2015-08-29 13:00
@ka3a4ok 
everything looks OK.
This code hasn't really changed in the new release, and it was tested on WS 2012 R2, WS 2008 R2 and Windows 7 Pro and it worked as expected.
Since you only have the problem with 2.8.2102 it may be something that changed in the code, but right now I don't see anything in that call stack and in those variables that could justify an error calling acceptex, unless there has been a silent failure before that acceptex call.
Let me check the code and I'll get back to you.
Thanks.

**Comment by ka3a4ok** [comment] 2015-08-29 13:01
Minor note: I use Windows 7 with SP1

**Comment by enricogior** [comment] 2015-08-29 13:05
I'm also testing this on a Windows 7 Pro SP1 box.

**Comment by enricogior** [comment] 2015-08-29 13:40
@ka3a4ok,
in win32_wsiocp.c put a breakpoint in WSIOCP_SocketAttach() line 137 and check it the function completes successfully returning 0 at the end. The return value is not checked by the caller so it could be the source of the silent failure.

**Comment by ka3a4ok** [comment] 2015-08-29 14:19
Yes, it's returns 0

**Comment by enricogior** [comment] 2015-08-29 14:38
@ka3a4ok 
I'm running out of possibilities, let's try with the buffer size, please in win32_wsiocp.c replace line 111:

```
areq->buf = CallocMemoryNoCOW(sizeof(struct sockaddr_storage) * 2 + 64);
```

with:

```
areq->buf = CallocMemoryNoCOW(sizeof(struct sockaddr_storage) * 2 + 128);
```

and lines 155-119:

```
result = FDAPI_AcceptEx(listenfd, acceptfd,
                        areq->buf, 0,
                        sizeof(struct sockaddr_storage),
                        sizeof(struct sockaddr_storage),
                        &bytes, &areq->ov);
```

with:

```
result = FDAPI_AcceptEx(listenfd, acceptfd,
                        areq->buf, 0,
                        sizeof(struct sockaddr_storage) + 32,
                        sizeof(struct sockaddr_storage) + 32,
                        &bytes, &areq->ov);
```

**Comment by ka3a4ok** [comment] 2015-08-29 15:00
No any effect. Still fails

**Comment by enricogior** [comment] 2015-08-29 15:07
@ka3a4ok 
I'm not surprised since there was nothing wrong to begin with.
We need to get the mswsock.dll symbols and step into the acceptex function to understand why it fails.

**Comment by ka3a4ok** [comment] 2015-08-29 15:25
This is stable issue, because i tried on four different machines with same effect.

**Comment by ka3a4ok** [comment] 2015-08-29 15:31
I just tried to run redis-server on my Virtual machine - everything is ok. Maybe it is something about multiple network adapters configuration?

**Comment by enricogior** [comment] 2015-08-29 15:59
@ka3a4ok,
it could be, how is your configuration?

**Comment by ka3a4ok** [comment] 2015-08-29 16:10
2 real adapters and 2 VmWare virtual adapters. I turned off Tcp/Ip v4 and Tcp/Ip v6 for every, except one real adapter, but no effect.

**Comment by enricogior** [comment] 2015-08-29 16:21
I will try with two physical adapters plus two virtual and I'll let you know.

**Comment by ravynz** [comment] 2015-09-01 14:59
I am also experiencing this same issue.  I was able to install it and run it in one environment, but not in another.  I haven't taken a dump but it is doing the same as described above, crash, no message, faulting module is ntdll.

Faulting application name: redis-server.exe, version: 0.0.0.0, time stamp: 0x55dc76ec
Faulting module name: ntdll.dll, version: 6.1.7601.18933, time stamp: 0x55a6a196
Exception code: 0xc0000374
Fault offset: 0x00000000000bffc2
Faulting process id: 0x5a4
Faulting application start time: 0x01d0e4c2ac544fe8

**Comment by enricogior** [comment] 2015-09-01 15:03
Hi @ravynz,
what are the hardware difference between the two environments?
Thank you.

**Comment by ravynz** [comment] 2015-09-01 15:23
I think the biggest different appears to be one environment only has a single vmware Ethernet adapter while the problem environment has 2 per machine.  There are various other differences as well, in processors, ram, etc.  The one that is having a problem is on windows server 2008 r2 sp1 w/ 4 gb ram and 2 vmware virtual Ethernet adapters.  It has nothing else running on it.

**Comment by enricogior** [comment] 2015-09-01 15:36
@ravynz 
to make sure I understand it right: the problem is on a VM guest that has two Ethernet adapters, correct?
What network connection type are those adapters using: Bridged directly to the physical network?

**Comment by enricogior** [comment] 2015-09-02 08:14
@ka3a4ok, @ravynz 
did you guys make any change to the config file?
Since the problem seems to be caused by Redis trying to bind to multiple network adapters, can you please try to specify only one adapter using the `bind` configuration flag?
Thank you.

**Comment by ravynz** [comment] 2015-09-02 13:30
I did have changes originally, but when it failed I used the default included config.  I will try what you suggested.  Some more specifics on the setup, it has two network adapters, one of which can reach out to the internet, the other is an interior backup network.  I have the ipconfig info if that is helpful.  Trying to use bind later today.

**Comment by enricogior** [comment] 2015-09-02 13:42
@ravynz 
if you can post the output of `ipconfig /all` that may help, thank you.

**Comment by ka3a4ok** [comment] 2015-09-03 07:57
Binding to IP in config file prevents crash.

**Comment by enricogior** [comment] 2015-09-03 08:24
@ka3a4ok,
this is good news.
Can you please provide more information regarding the IP that causes the crash?
The output of `ipconfig /all` would be a good starting point to understand the problem.
Thank you.

**Comment by enricogior** [comment] 2015-09-03 14:59
@ka3a4ok, @ravynz,
I have a fix for the crash.
Since I don't have a machine that reproduces the problem, to be sure the fix works I prepared a private build, the MSI and the zip folder are available here: http://1drv.ms/1JBg0wB
If you can try the private build, let me know if it fixes the problem.
Thank you very much.

**Comment by ravynz** [comment] 2015-09-03 15:13
The private build started up for me.

**Comment by enricogior** [comment] 2015-09-03 16:58
@ravynz 
thank you.

**Comment by ka3a4ok** [comment] 2015-09-03 17:49
It seems fixed. Started without any problems.

**Comment by enricogior** [comment] 2015-09-03 18:17
@ka3a4ok 
great, thank you.

**Comment by enricogior** [comment] 2015-09-08 14:18
@ka3a4ok, @ravynz 
the new [release 2.8.2103](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2103) contains the fix for this issue.
Thank you.

**Closed as completed by enricogior** 2015-09-08 14:18 UTC
Labels: Bug, Solved
