### ISSUE TITLE
3.0.300-alpha3   hiredis : 'redefinition' errors in Win32_FDAPI.h

### ISSUE THREAD

**Issue by uwaw12** [microsoftarchive/redis#333] opened 2015-10-06 15:50 UTC
error   1   error C2371: “off_t”: redefinition；   d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_types.h 37  1   db_redis
error   2   error C4005: “INCL_WINSOCK_API_PROTOTYPES”: redefinition    d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 35  1   db_redis
error   3   error C2365: “accept”: redefinition；previous definition was 'function'    d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 156 1   db_redis
error   4   error C2365: “access”: redefinition；previous definition was 'function'    d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 157 1   db_redis
error   5   error C2365: “bind”: redefinition；previous definition was 'function'  d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 158 1   db_redis
error   6   error C2365: “connect”: redefinition；previous definition was 'function'   d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 159 1   db_redis
error   7   error C2365: “getsockopt”: redefinition；previous definition was 'function'    d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 166 1   db_redis
error   8   error C2365: “getpeername”: redefinition；previous definition was 'function'   d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 167 1   db_redis
error   9   error C2365: “getsockname”: redefinition；previous definition was 'function'   d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 168 1   db_redis
error   10  error C2365: “htonl”: redefinition；previous definition was 'function' d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 169 1   db_redis
error   11  error C2365: “htons”: redefinition；previous definition was 'function' d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 170 1   db_redis
error   12  error C2365: “isatty”: redefinition；previous definition was 'function'    d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 171 1   db_redis
error   13  error C2365: “listen”: redefinition；previous definition was 'function'    d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 174 1   db_redis
error   14  error C2365: “ntohl”: redefinition；previous definition was 'function' d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 176 1   db_redis
error   15  error C2365: “ntohs”: redefinition；previous definition was 'function' d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 177 1   db_redis
error   16  error C2365: “open”: redefinition；previous definition was 'function'  d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 178 1   db_redis
error   17  error C2365: “read”: redefinition；previous definition was 'function'  d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 181 1   db_redis
error   18  error C2365: “select”: redefinition；previous definition was 'function'    d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 182 1   db_redis
error   19  error C2365: “setsockopt”: redefinition；previous definition was 'function'    d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 183 1   db_redis
error   20  error C2365: “socket”: redefinition；previous definition was 'function'    d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 184 1   db_redis
error   21  error C2365: “write”: redefinition；previous definition was 'function' d:\drong\dependencies\hiredis\redis-win\src\win32_interop\win32_fdapi.h 185 1   db_redis

error   24  error LNK2005: _inet_pton already defined in Win32_Interop_d.lib(Win32_FDAPI.obj)  d:\drong_socket_d.pyd(socketmodule.obj)

main.h:
# include "hiredis.h"
# define NO_QFORKIMPL
# include "win32fixes.h"
# ifdef _DEBUG
# pragma comment (lib, "hiredis_d.lib")
# pragma comment (lib, "Win32_Interop_d.lib")
# else
# pragma comment (lib, "hiredis.lib")
# pragma comment (lib, "Win32_Interop.lib")
# endif

**Comment by enricogior** [comment] 2015-10-13 11:18
Hi @uwaw12,
I'm closing this since is a duplicate of https://github.com/MSOpenTech/redis/issues/225

**Closed as completed by enricogior** 2015-10-13 11:18 UTC
