### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by nvskarunakar** [microsoftarchive/redis#357] opened 2015-11-18 15:27 UTC
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[7936] 18 Nov 10:23:50.202 # --- ABORT
[7936] 18 Nov 10:23:50.203 # --- STACK TRACE
redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktra
ce.cpp:95)(0x00000016, 0x40149A50, 0x00000000, 0x00000001)
redis-server.exe!AbortHandler(c:\release\redis\src\win32_interop\win32_stacktrac
e.cpp:206)(0x00000016, 0x6C719AA3, 0x4012C210, 0x76F18FDA)
redis-server.exe!raise(f:\dd\vctools\crt\crtw32\misc\winsig.c:587)(0x00000001, 0
x00000000, 0x00000040, 0x00000030)
redis-server.exe!abort(f:\dd\vctools\crt\crtw32\misc\abort.c:82)(0x00000001, 0x4
00382F6, 0x4012C210, 0x0012F810)
redis-server.exe!dlmalloc(c:\release\redis\src\win32_interop\win32_dlmalloc.c:46
38)(0x00000030, 0x00000009, 0x00000001, 0x4012C210)
redis-server.exe!zmalloc(c:\release\redis\src\zmalloc.c:143)(0x0012F8A0, 0x00000
009, 0x40135918, 0x00000006)
redis-server.exe!rdbSaveRio(c:\release\redis\src\rdb.c:681)(0x4012C210, 0x000000
80, 0x00000000, 0x0474275C)
redis-server.exe!rdbSave(c:\release\redis\src\rdb.c:760)(0x00000080, 0x00000000,
 0x00000080, 0x00000080)
redis-server.exe!QForkChildInit(c:\release\redis\src\win32_interop\win32_qfork.c
pp:305)(0xFFFFFFFF, 0x00000000, 0x03740000, 0x00000090)
redis-server.exe!QForkStartup(c:\release\redis\src\win32_interop\win32_qfork.cpp
:747)(0x00390250, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1348)(0
x00000000, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!__tmainCRTStartup(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(
0x00000000, 0x00000000, 0x00000000, 0x00000000)
kernel32.dll!BaseThreadInitThunk(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x
00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x0000
0000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x0000
0000, 0x00000000, 0x00000000, 0x00000000)
[7936] 18 Nov 10:23:50.646 #
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by enricogior** [comment] 2015-11-18 15:38
Hi @nvskarunakar 
this is basically the same problem described in #355 
For how long was the server running before the crash happened?
The fix for this would be to change the current memory allocation mechanism. 
We have done that for the 3.0 branch and we may port that change to the 2.8 later on.
You may consider evaluating the [3.0 RC1](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.500-rc1).
Thank you.

**Comment by nvskarunakar** [comment] 2015-11-18 16:52
The server was running for only about an hour before it crashed. It was not having a great load I would say. I will try the 3.0 RC1 out. Thank you!

**Comment by enricogior** [comment] 2016-01-25 10:50
Closing this issue since is a duplicate of #355.
Thank you.

**Closed as completed** 2016-01-25 10:50 UTC
