### ISSUE TITLE
'redefinition' errors in Win32_FDAPI.h

### ISSUE THREAD

**Issue by kehlert** [microsoftarchive/redis#225] opened 2015-03-02 23:34 UTC
When I include hiredis.h, I get these errors like this:

...\redis-2.8.19\deps\hiredis....\src\win32_Interop\Win32_FDAPI.h(220): error C2365: 'open' : redefinition; previous definition was 'function'
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\io.h(336) : see declaration of 'open'

That was the error for 'open', and I also get errors for 'read', 'write', 'isatty', and 'access'. It turns out that io.h is included by the Google test library 'gtest', and I include the gtest headers before hiredis.h. Any suggestions for what to do besides including the headers in a certain order? It would be best to avoid that solution, because otherwise someone on this project will run into the same problem again and again.

Edit: I tried reordering the includes such that hiredis.h is included before the gtest headers, but that doesn't work. When the gtest headers include io.h, then compiling io.h fails due to 'redefinition' errors.

**Comment by orangemocha** [comment] 2015-03-10 15:46
Thanks for reporting this issue, @kehlert .

Our code redefines some io.h functions (read, write, etc) to make sure that redis code which uses those functions to operate on sockets works on Windows. As far as I can tell, that makes sense for porting the redis code base, but affecting code that includes hiredis.h is an unwanted side effect. I will investigate refactoring our definitions to address this issue.

In the meantime, you could try the following workarounds:
1) Try the following inclusion sequence
#define  __STDC__ 1
#include <io.h> // or whatever header is including io.h
#include "hiredis.h"

2) Alternatively, you could try separating the code that (indirectly) includes io.h and hiredis.h into different source files.

Also, if you are able to share your code to reproduce this issue, that might be helpful.
Thanks!

**Comment by orangemocha** [comment] 2015-03-10 15:49
Thanks for reporting this issue, @kehlert .

Our code redefines some io.h functions (read, write, etc) to make sure that redis code which uses those functions to operate on sockets works on Windows. As far as I can tell, that makes sense for porting the redis code base, but affecting code that includes hiredis.h is an unwanted side effect. I will investigate refactoring our definitions to address this issue.

In the meantime, you could try the following workarounds:
1) Try the following inclusion sequence

```
#define  __STDC__ 1
#include <io.h> // or whatever header is including io.h
#include "hiredis.h"
```

2) Alternatively, you could try separating the code that (indirectly) includes io.h and hiredis.h into different source files.

Also, if you are able to share your code to reproduce this issue, that might be helpful.
Thanks!

**Comment by yacoder** [comment] 2015-08-28 23:08
I think the same issue that occurs in other contexts, when some of the symbols conflict with symbols from WS2_32.dll, as described in this blog post: http://hostagebrain.blogspot.com/2015/04/linking-problem-with-c.html

I've used the approach described in the blog to rename the internal symbols during build, would you accept a pull request to update the msvs projects with such redefinitions? Alternatively, maybe renaming the actual functions in code would be better?

**Comment by enricogior** [comment] 2015-08-29 07:34
Hi @yacoder,
in your project do you use the Win32_Interop lib directly or are you using hiredis that in turn uses Win32_Interop?

We are making significant changes to the Win32_Interop in the 3.0 branch.
The problem with the WSA functions redefinition is fixed in the upcoming 3.0 alpha3 release.

The pthread functions will have their own header file and it will be included only where it's strictly required so it shouldn't cause a linking problem anymore.

For the posix functions such as socket() it's still work in progress. Renaming those functions is not our first option since they are used in the antirez/redis code as well and we don't want to change that code since we are actually removing as much Windows-specific code as possible from the antirez/redis code to make merging new releases simpler.

On the long term Win32_Interop will be split in two libs one to be used by hiredis and the other one with support for redis-server, currently hiredis is linking several things that are only required when compiling redis-server.
hiredis includes win32_Interop/win32fixes.h that in turn includes a lot of things that are not needed and we are fixing that.
The goal is to make hiredis a stand alone lib that can be easily linked in external project, all the input from the community is welcome.
I'll let you know as soon as we release 3.0 alpha3, so you can send feedback and propose changes based on that code, sounds good?
Thank you.

**Comment by yacoder** [comment] 2015-08-30 00:27
@enricogior thanks, I'm linking to hiredis.lib and would really like to see it better isolated from the rest. In adition to those symbols, there's also the `off_t` type redefined, which isn't used by hiredis as far as I can tell, but is declared in one of the interop headers included from hiredis headers. It would be great if that redefinition is also removed from the hiredis headers, I don't think it is a good idea to redefine those types, and I don't think anyone would want to re-define off_t in their codebase just to be able to use hiredis.

I'm interested in 3.0 features, but I'm not sure I'll have time in near future to try it out... but will keep an eye :-)

**Comment by enricogior** [comment] 2015-08-30 10:17
@yacoder 
thanks for the suggestion, off_t will be removed from the hiredis headers.
Regarding 3.0: hiredis hasn't changed from 2.8 to 3.0. We decided to do the work to isolate the hiredis lib on the 3.0 branch because we didn't want to cause problems to whom is currently using it on the 2.8 branch. But it should be simple to switch from hiredis 2.8 to hiredis 3.0 when we release the stable version.

**Comment by enricogior** [comment] 2016-01-25 16:48
From now on for hiredis and hiredis issues please visit https://github.com/Microsoft/hiredis.
Thank you.

**Closed as completed by enricogior** 2016-01-25 16:48 UTC
Labels: P2, hiredis

**Comment by Markgorden** [comment] 2016-10-11 01:51
I use other way fix this issue at https://github.com/Markgorden/Win32_Interop
I don't know whether is it good for you?
