### ISSUE TITLE
Redis 3.0

### ISSUE THREAD

**Issue by danesparza** [microsoftarchive/redis#231] opened 2015-04-01 16:57 UTC
Redis 3.0 [is now stable](http://redis.io/) -- when can we expect a Windows version?

**Comment by chester89** [comment] 2015-04-01 19:55
:+1:

**Comment by christoth** [comment] 2015-04-02 12:13
+1

**Comment by nmehlei** [comment] 2015-04-02 12:27
+1

**Comment by danieleteti** [comment] 2015-04-02 13:37
+1
Il 02/apr/2015 02:27 PM "nmehlei" notifications@github.com ha scritto:

**Comment by mikestu** [comment] 2015-04-02 18:07
+1

**Comment by davidjrh** [comment] 2015-04-02 20:59
+1

**Comment by cugljd** [comment] 2015-04-03 07:38
+1

**Comment by g1ga** [comment] 2015-04-03 09:48
+1

Il giorno ven 3 apr 2015 alle ore 09:38 cugljd notifications@github.com
ha scritto:

**Comment by azhozhin** [comment] 2015-04-03 12:12
+1

**Comment by james-andrewsmith** [comment] 2015-04-04 05:01
+1

**Comment by Scratch-net** [comment] 2015-04-05 06:50
+100

**Comment by Eyads** [comment] 2015-04-05 07:14
+1
Any rough estimations? Can't wait to use the Redis Cluster.

**Comment by glikoz** [comment] 2015-04-06 12:32
+1 :)

**Comment by evgenyk** [comment] 2015-04-06 23:56
We're looking into using redis cluster on Windows, any idea if you're going to get back to it? The last commit seemed to have happened a month ago ;) //cc @orangemocha

**Comment by cpunella** [comment] 2015-04-09 15:14
+1

**Comment by djcameron** [comment] 2015-04-10 17:14
+1 clustering!

**Comment by tellan55** [comment] 2015-04-10 18:14
+1

**Comment by jiangzhuo** [comment] 2015-04-15 03:51
+1

**Comment by guo9310** [comment] 2015-04-16 03:05
+1

**Comment by lubberscorrado** [comment] 2015-04-16 12:07
+1

**Comment by PritamUpadhyay** [comment] 2015-04-17 05:07
+1

**Comment by bcw104** [comment] 2015-04-17 06:14
+1

**Comment by ceee** [comment] 2015-04-20 18:53
+1

**Comment by netren20000** [comment] 2015-04-21 02:05
+1

**Comment by wumingwuan** [comment] 2015-04-21 15:08
+1

**Comment by orangemocha** [comment] 2015-04-22 18:28
Hello all. We are still evaluating the work that needs to be done to port 3.0 to Windows and what resources we can allocate to it. I can’t say for sure when we’ll have a better answer, but I am confident that it won’t be long.

2.8 is certainly still supported (albeit with limited resources).

**Comment by matthiasg** [comment] 2015-04-24 14:42
beware: _rant_

@orangemocha  ... the reaction time on this issue is what saddens me. It took **21 days** to answer @danesparza that you dont know whether you even have resources to allocate ! On top of that, there might not even be any long-term support for 2.8, quoting limited resources.

projects like redis and thousands of others are important to get anything done for modern server based applications. We are already NOT using windows on servers anymore because the quality of projects such as redis on windows is lagging behind and some projects are just MIA.

We are still developing on Windows for now, so we try to make sure our system works on windows at least for that, but that will go away too.

Now of course we could invest into keeping the windows port of redis alive and up-to-date ourselves, or we could look for redis-like alternatives on Windows. But its so much easier to just not use Windows anymore.

Microsoft seems to not fully grasp why they have to invest into projects like this and make them as great as they can be.

I am thankful for all the work MS did put into this, but i do fear this was for naught. 

PS: BTW i just added to chromium pdf rendering bugs a few days ago, documented them to reproduce. One is already fixed, one is being triaged right now. I don't really like a lot of what Google does, but that level of transparency and professional courtesy is paying off.

PPS: If this where a private project none of this would apply, but what is https://msopentech.com/opentech-projects/ about ?

**Comment by joe-udwin-lrn** [comment] 2015-04-30 14:37
+1

**Comment by DivineTraube** [comment] 2015-04-30 14:55
+1

**Comment by at0717** [comment] 2015-04-30 15:45
+1

**Comment by aharpervc** [comment] 2015-05-01 13:58
+1 and another +1 for @matthiasg 's comment about communications issues

**Comment by gwicksted** [comment] 2015-05-12 14:26
+1

**Comment by nmehlei** [comment] 2015-05-12 14:39
...though I rather have a rock-stable 2.8 than a newly-possibly-unstable 3.0 ;)

**Comment by matthiasg** [comment] 2015-05-13 08:36
sure we want something stable .. that wasnt my point. but as with any open source project i want to gauge what the likelihood of abandonment is before i build on it and that includes keeping issue fixes etc merged in (also in 'stable' 2.8 branches etc). 

right now i see three options for us: dont use redis at all, dont use windows server side (use unix instead), fork redis on windows and keep it updated ourselves. 

these options apply to practically all open source projects that we use. most of them work fine on windows out-of-the-box so its not a big deal, but many already work better on unix so just not using windows is the clear option for us. 

the only reasons we still like to include windows support are: 1) some developers use windows client pcs, its nice to have our servers run here directly 2) some customers still have windows servers and this way we dont have to pressure them to change.

**Comment by bluebear94** [comment] 2015-05-17 20:44
+1. I have plenty of other stuff that needs Windows.

**Comment by stefanprodan** [comment] 2015-05-19 14:26
+1

**Comment by gustavoq-infocorp** [comment] 2015-05-20 13:03
+1

**Comment by 1ph** [comment] 2015-05-21 04:35
+100500

**Comment by rswillis** [comment] 2015-06-02 16:30
Hi, has there been any progress?  particularly interested in cluster feature, as well as a clear statement of intent here around future development before we adopt.  

Love the work so far.  seemed like a great addition.

**Comment by orangemocha** [comment] 2015-06-03 17:30
I am happy to announce that the work to port Redis 3.0 to Windows [has started](https://github.com/MSOpenTech/redis/commits/3.0-winport)! 

The plan is to start rolling out some pre-releases in the next few weeks to gather early feedback from the community, even though the code will not be completely functional or stable. It’s difficult to predict when we can have the first “stable” release, but I am hoping that that can happen sometime in the next 2-3 months.

**Comment by gwicksted** [comment] 2015-06-05 12:35
Thank you!!

**Comment by davidjrh** [comment] 2015-06-05 12:36
Superawesome news!!!!

**Comment by chester89** [comment] 2015-06-05 13:18
​Awesome news. Keep us posted​

2015-06-05 15:36 GMT+03:00 David Rodríguez notifications@github.com:

> Superawesome news!!!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/231#issuecomment-109281655.

## 

Yours faithfully,
Gleb

**Comment by danieleteti** [comment] 2015-06-05 13:23
Great News!!!

2015-06-05 15:19 GMT+02:00 Gleb Chermennov notifications@github.com:

> ​Awesome news. Keep us posted​
> 
> 2015-06-05 15:36 GMT+03:00 David Rodríguez notifications@github.com:
> 
> > Superawesome news!!!!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MSOpenTech/redis/issues/231#issuecomment-109281655.
> 
> ## 
> 
> Yours faithfully,
> Gleb
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/231#issuecomment-109290969.

## 

_Daniele Teti_
CEO
bit Time Professionals
web: www.bittimeprofessionals.it http://www.bittime.it
blog: www.danieleteti.it
books: www.danieleteti.it/delphi-cookbook
mobile: +39 3496626822
office: +39 06 83393029

**Comment by matthiasg** [comment] 2015-06-08 05:38
Great! I really think MS could do some really good work here if they keep at this.. e.g using the know-how embedded in their company to more thoroughly test/reproduce/combat issues such as https://aphyr.com/posts/307-call-me-maybe-redis-redux when the time comes...

**Comment by nblackburn** [comment] 2015-06-10 09:20
+1

**Comment by ran-jit** [comment] 2015-07-18 16:14
+1

**Comment by enricogior** [comment] 2015-07-22 13:24
We are happy to announce that the first **alpha** release for **Redis on Windows 3.0** is available.
[v3.0.100-alpha1](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.100-alpha1) is an alpha release in all respects: feel free to install it and play with it, please send feedback, but **don't use it in production**.

The release is based on antirez/redis 3.0.1 code base (the next alpha release will include the latest antirez/redis release).

The current build has been tested only using the standard tests: 
- 36 out of 37 the unit tests passed. The single test failure is not critical. Some tests may occasionally fail because of short timeouts in the validation code.
- All the sentinel tests passed.
- 10 out of 11 cluster tests passed. Two tests failed for a bug that seems to effect only the [CLIENT KILL](http://redis.io/commands/client-kill) command, a temp workaround for the that bug made the two test pass, leaving only 1 cluster test not passing.

When sending feedback, please add a "3.0" prefix in the issue's title.
Thank you :)

**Comment by chester89** [comment] 2015-07-22 14:03
Nice. When can we expect an update for NuGet/Chocolatey packages?

2015-07-22 16:24 GMT+03:00 Enrico Giordani notifications@github.com:

> We are happy to announce that the first _alpha_ release for _Redis on
> Windows 3.0_ is available.
> v3.0.100-alpha1
> https://github.com/MSOpenTech/redis/releases/tag/win-3.0.100-alpha1 is
> an alpha release in all respects: feel free to install it and play with it,
> please send feedback, but _don't use it in production_.
> 
> The release is based on antirez/redis 3.0.1 code base (the next alpha
> release will include the latest antirez/redis release).
> 
> The current build has been tested only using the standard tests:
> - 36 out of 37 the unit tests passed. The single test failure is not
>   critical. Some tests may occasionally fail because of short timeouts in the
>   validation code.
> - All the sentinel tests passed.
> - 10 out of 11 cluster tests passed. Two tests failed for a bug that
>   seems to effect only the CLIENT KILL
>   http://redis.io/commands/client-kill command, a temp workaround for
>   the that bug made the two test pass, leaving only 1 cluster test not
>   passing.
> 
> When sending feedback, please add a "3.0" prefix in the issue's title.
> Thank you :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/231#issuecomment-123718137.

## 

Yours faithfully,
Gleb

**Comment by enricogior** [comment] 2015-07-22 14:07
Hi @chester89,
for the alpha releases we are not planning to release the NuGet/Chocolatey packages.
Do you need signed binaries? If that is a blocking issue let me know.

**Comment by chester89** [comment] 2015-07-22 14:29
​Some of my scripts that deploy/configure Redis instances rely on
NuGet/Chocolatey - not really an issue, I'll be fine without them.​

2015-07-22 17:07 GMT+03:00 Enrico Giordani notifications@github.com:

> Hi @chester89 https://github.com/chester89,
> for the alpha releases we are not planning to release NuGet/Chocolatey
> packages.
> Do you need signed binaries? If that is a blocking issue let me know.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/231#issuecomment-123734244.

## 

Yours faithfully,
Gleb

**Comment by gwicksted** [comment] 2015-07-22 15:25
Hi Enricogior, you could do an alpha nuget package that will not push to everyone by default:

> Additionally, prerelease versions of your API can be denoted by appending an arbitrary string to the Patch number separated by a dash. For example:
> 
> 1.0.1-alpha

[NuGet Versioning](https://docs.nuget.org/create/versioning)

**Comment by enricogior** [comment] 2015-08-20 13:33
Today a new alpha [release 3.0.3-alpha2](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.300-alpha2) is available.

The release is based on antirez/redis 3.0.3 code base.

The NuGet and Chocolatey packages will not be available for this release.

As for the previous alpha release: feel free to install it and play with it, please send feedback, but **don't use it in production**.

When sending feedback, please add a "3.0" prefix in the issue's title.
Thank you :)

**Comment by milaney** [comment] 2015-08-22 14:27
Splendid work!

**Comment by enricogior** [comment] 2015-09-02 13:32
[Release 3.0.300-alpha3](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.300-alpha3) is available.

The MSI version number is still 3.0.300, therefore if you have the alpha2 installed, uninstall the alpha2 first and then install the alpha3.

Compared to the alpha2 release it brings Windows-specific bug fixes.
The NuGet and Chocolatey packages will not be available for this release.

As for the previous alpha release: feel free to install it and play with it, please send feedback, but **don't use it in production**.

**Comment by rpannell** [comment] 2015-09-03 12:25
Is there a possible date on when 3.0 will be in release version or at best in beta?  We are currently installing redis in test and production later this month with master and slave for some type of fail over, but would like to have a true balanced solution if at all possible.  The higher ups are wondering when we could move to 3 and if would be best to wait it out.

By the way GREAT WORK!  Loving seeing solid linux based open source projects ported over to MS!

**Comment by enricogior** [comment] 2015-09-03 12:36
Hi @rodgod20,
we hope to have a beta soon, but we aren't ready to commit to a date yet.
We are working on removing the memory mapped file limitation that has been the source of many issues on 2.8.x. It's a major architecture change compared to 2.8 and it will require a lot of testing before being ready for production.
Thank you.

**Comment by rpannell** [comment] 2015-09-03 12:48
First thanks for the quick reply!  Secondly, thanks for the info and I completely understand!  When it goes beta I will hopefully have the ability to drop it in our test environment to hopefully give some feedback.

**Comment by enricogior** [comment] 2015-09-03 13:16
@rodgod20,
looking forward to get feedback on the beta.
Thank you.

**Comment by rapoth** [comment] 2015-09-04 20:03
Thank you for the great work! Does the alpha release also support the cluster mode?

**Comment by enricogior** [comment] 2015-09-04 22:37
Hi @rapoth,
yes it does, all the cluster tests passed.

**Comment by enricogior** [comment] 2015-10-14 14:25
We are very happy to announce that the first **beta** release for Redis on Windows 3.0 is available.
[v3.0.300-beta1](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.300-beta1) is a beta release: feel free to install it and play with it, please send feedback, but **don't use it in production**.

The release is based on antirez/redis 3.0.3 code base .
Compared to the previous alpha releases there are significant Windows-specific changes regarding the memory management: starting with this release Redis on Windows doesn't use anymore the memory mapped file (i.e. RedisQFork_*.dat) and uses a new memory allocator that should provide better performance and less heap fragmentation.

More information is available [in the wiki](https://github.com/MSOpenTech/redis/wiki/Memory-Configuration-For-Redis-3.0).

When sending feedback, please add a "3.0" prefix in the issue's title.
Thank you :)

_edited_ to add the link to the [source code](https://github.com/MSOpenTech/redis/tree/3.0).

**Comment by markpjohnson** [comment] 2015-11-11 20:53
Is there a target release date for Redis 3.0? Giving a target month or quarter would be extremely helpful.

**Comment by enricogior** [comment] 2015-11-11 21:07
Hi @markpjohnson,
the 3.0 Release Candidate will be publish this week.
Depending on the feedback on the RC we will target a final release. In the best case it will be early December, but we can't guarantee it right now. It may be January if the RC will not meet the quality target.

**Comment by enricogior** [comment] 2015-11-12 20:58
The first **Release Candidate** (RC1) of Redis on Windows 3.0 is available: [v3.0.500-rc1](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.500-rc1).

What's new since the Beta1?
- Merged the 3.0.4 and 3.0.5 releases from antirez/redis plus Windows-specific fixes.
- Merged four Pull Requests: nuget support, sentinel notification script, announce-ip and announce-port commands, visual studio configuration changes.
- Fixed networking issues.

This release **is not yet approved** to be used in a production environment.
Please test it in your staging environment and send us your feedback.
Thank you!

**Comment by enricogior** [comment] 2015-12-03 08:31
The second **Release Candidate** (RC2) of Redis on Windows 3.0 is available: [v3.0.500-rc2.](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.500-rc2)

What's new since the RC1?
- Fixed a bug that was causing the child process to crash.
- Fixed a bug that was causing replication to fail when the master uses authentication.
- Merged PR fixes for x86 build (we still don't support x86 officially)

This release **is not yet approved** to be used in a production environment.
Please test it in your staging environment and send us your feedback, the more feedback we will get the faster we can reach the stable release for 3.0.
Thank you!

**Comment by divmgl** [comment] 2015-12-04 03:29
Happy to see that Redis love on Windows. Currently using it in my development environment, cheers.

**Comment by enricogior** [comment] 2015-12-07 19:44
The RC2 has been promoted to [stable](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.500).
This is the first [stable release](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.500) of Redis on Windows 3.0.

Even if this release has been approved for production, make sure you test it in your testing/staging enviroment before using it in production.

Please send you feedback and report issues if you run into any problem.
Thank you.

**Comment by enricogior** [comment] 2015-12-08 12:14
Closing the issue since the stable version has been released :)

**Closed as completed by enricogior** 2015-12-08 12:14 UTC

**Comment by matthiasg** [comment] 2015-12-08 16:38
congrats. and up-to-date with redis at 3.0.5. time to test more deeply.
