### ISSUE TITLE
ERR unknown command 'pfadd'

### ISSUE THREAD

**Issue by sedouard** [microsoftarchive/redis#227] opened 2015-03-12 19:20 UTC
Trying redis out on my local machine with version 2.8.19. I start up:

```
redis-server.exe reds.windows.conf
```

Afterwards in the CLI I'm trying PFADD and I see:

```
127.0.0.1:6379> pfadd
(error) ERR unknown command 'pfadd'
127.0.0.1:6379> help pfadd

  PFADD key element [element ...]
  summary: Adds the specified elements to the specified HyperLogLog.
  since: 2.8.9
  group: 
```

This command works fine in the linux and osx build. Weird that it recognizes it as a command in help but not when its actually invoked.

Nobody seems to have posted about this. Any pointers appreciated.

**Comment by chester89** [comment] 2015-03-13 08:54
Is there a possibility you renamed it?

**Comment by sedouard** [comment] 2015-03-13 14:36
Nope. I pulled the newest binary straight from the msopentech releases page. Running the command in node.js seemed to just hang.

**Comment by orangemocha** [comment] 2015-03-23 19:34
Hi @sedouard . This is quite strange. I just downloaded and unzipped 2.8.19 from the releases page (https://github.com/MSOpenTech/redis/releases/download/win-2.8.19/redis-2.8.19.zip) and followed the same steps you mentioned. I get:
127.0.0.1:6379> pfadd
(error) ERR wrong number of arguments for 'pfadd' command

Is it possible that there is an older version of redis-server.exe in your path? Does the output of 'info server' confirm that you are running 2.8.19?

**Comment by maxwellb** [comment] 2015-03-23 21:34
I'll leave another "works for me". Love the HLL commands. Glad to verify this works over here.

**Comment by orangemocha** [comment] 2015-05-04 17:14
I cannot reproduce this issue. Closing for now. @sedouard  if the issue persists please let us know.

**Closed as completed by orangemocha** 2015-05-04 17:14 UTC
