### ISSUE TITLE
crash with Redis-x64-2.8.2102

### ISSUE THREAD

**Issue by Freundschaft** [microsoftarchive/redis#306] opened 2015-09-02 15:15 UTC
crashdump at http://we.tl/HBphuyAfrb

**Comment by Freundschaft** [comment] 2015-09-02 15:16
I also have this from VS

Ausnahmefehler bei 0x00007FFA3E3EA28C (ntdll.dll) in redis-server.exe: 0xC0000374: Ein Heap wurde beschädigt (Parameter: 0x00007FFA3E442180)

Seams like heap corruption

**Comment by enricogior** [comment] 2015-09-02 17:15
Hi @Freundschaft 
the crash is happening when Redis starts?

**Comment by Freundschaft** [comment] 2015-09-02 22:24
yes. I am starting it with maxheap 4GB

**Comment by enricogior** [comment] 2015-09-02 22:36
@Freundschaft 
so this is the same problem as https://github.com/MSOpenTech/redis/issues/304
The machine is a virtual machine or a physical machine?
Does the machine have multiple network adapters?
If it does, can you try starting Redis setting the `bind` flag to bind to only one adapter at the time?
Thank you.

**Comment by enricogior** [comment] 2015-09-03 14:59
Hi @Freundschaft 
I have a fix for the crash.
Since I don't have a machine that reproduces the problem, to be sure the fix works I prepared a private build, the MSI and the zip folder are available here: http://1drv.ms/1JBg0wB
If you can try the private build, let me know if it fixes the problem.
Thank you very much.

**Comment by Freundschaft** [comment] 2015-09-04 08:54
works indeed, but out of some weird reason the service install fails during setup, it says I have unsufficient privileges to install services ?

**Comment by Freundschaft** [comment] 2015-09-04 09:00
okay its only with service-run flag that fails running

**Comment by Freundschaft** [comment] 2015-09-04 09:01
okay worked onw, seems like there was a problem with my NT authority account and permissions, but the build you provided fixed the crash for me, thanks!

**Comment by enricogior** [comment] 2015-09-04 09:03
Hi @Freundschaft 
thank you for the feedback.

**Comment by enricogior** [comment] 2015-09-08 14:17
@Freundschaft 
the [official build 2.8.2103](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2103) that contains the fix has been released.
Thank you.

**Closed as completed by enricogior** 2015-09-08 14:17 UTC
Labels: Solved

**Comment by Freundschaft** [comment] 2015-09-08 14:20
thanks a lot!
