### ISSUE TITLE
accept: Unknown error

### ISSUE THREAD

**Issue by ipanocloud** [microsoftarchive/redis#175] opened 2014-10-09 02:04 UTC
[4252] 08 Oct 21:13:52.873 - 0 clients connected (0 slaves), 4379184 bytes in use
[4252] 08 Oct 21:13:53.518 # Accepting client connection: accept: Unknown error
[5820] 08 Oct 21:13:54.888 # Server started, Redis version 2.8.12

**Comment by jepickett** [comment] 2014-10-10 02:59
Is this something you can reproduce?

**Comment by ipanocloud** [comment] 2014-10-10 03:08
I'm sorry, but only once.But it leads to redis

**Comment by jepickett** [comment] 2014-10-20 21:44
All the error indicates is that an error occurred during an accept() connection sequence. The problem could be in the server, client or the network stack. Without a scenario that reproduces the error, I will be unable to diagnose the source of the problem. I am closing this issue at this point due to lack of a reproduction scenario.

**Closed as completed by jepickett** 2014-10-20 21:44 UTC
