### ISSUE TITLE
Cannot Install Redis 2.8 on Windows

### ISSUE THREAD

**Issue by osherdo** [microsoftarchive/redis#278] opened 2015-07-30 16:32 UTC
When trying to install the version above I get the following error message:

service 'Redis'(Redis) failed to start. verify that you have sufficient proviliges to start system services.

Tried to google the problem but nothing seems to work.

How do I fix this issue?

(I am running windows 7 on VirtualBox)

**Comment by enricogior** [comment] 2015-07-30 16:41
Hi @osherdo,
thank you for reporting the issue. I'll close this one as a duplicate of #276

**Closed as completed by enricogior** 2015-07-30 16:41 UTC

**Comment by osherdo** [comment] 2015-07-30 16:45
@enricogior thanks.
