### ISSUE TITLE
RejoinCOWPages: MapViewOfFileEx

### ISSUE THREAD

**Issue by StefanPlizga** [microsoftarchive/redis#327] opened 2015-10-01 20:16 UTC
Hello,

Redis (build 2103) encountered a crash (no crash dump generated) on the slave with error EndForkOperation: 0x000001e7 - RejoinCOWPages: MapViewOfFileEx failed.: unknown error

This is the first time I see this error, I paste few lines before and after it. I have no idea of what this error means.

[4296] 01 Oct 21:58:51.785 - DB 0: 3206 keys (3206 volatile) in 8192 slots HT.
[4296] 01 Oct 21:58:51.785 - 50 clients connected (0 slaves), 836888216 bytes in use
[4296] 01 Oct 21:58:57.254 - DB 0: 3196 keys (3196 volatile) in 8192 slots HT.
[4296] 01 Oct 21:58:57.254 - 50 clients connected (0 slaves), 832252320 bytes in use
[4296] 01 Oct 21:59:02.722 - DB 0: 3195 keys (3195 volatile) in 8192 slots HT.
[4296] 01 Oct 21:59:02.722 - 50 clients connected (0 slaves), 834275744 bytes in use
[4296] 01 Oct 21:59:08.191 - DB 0: 3187 keys (3187 volatile) in 8192 slots HT.
[4296] 01 Oct 21:59:08.191 - 50 clients connected (0 slaves), 831275360 bytes in use
[4296] 01 Oct 21:59:13.660 - DB 0: 3187 keys (3187 volatile) in 8192 slots HT.
[4296] 01 Oct 21:59:13.660 - 50 clients connected (0 slaves), 832179408 bytes in use
[4296] 01 Oct 21:59:19.129 - DB 0: 3189 keys (3189 volatile) in 8192 slots HT.
[4296] 01 Oct 21:59:19.129 - 50 clients connected (0 slaves), 833250616 bytes in use
[4296] 01 Oct 21:59:24.597 - DB 0: 3194 keys (3194 volatile) in 8192 slots HT.
[4296] 01 Oct 21:59:24.597 - 50 clients connected (0 slaves), 834998456 bytes in use
[4296] 01 Oct 21:59:30.066 - DB 0: 3204 keys (3204 volatile) in 8192 slots HT.
[4296] 01 Oct 21:59:30.066 - 50 clients connected (0 slaves), 836539656 bytes in use
[4296] 01 Oct 21:59:35.535 - DB 0: 3204 keys (3204 volatile) in 8192 slots HT.
[4296] 01 Oct 21:59:35.535 - 50 clients connected (0 slaves), 835436096 bytes in use
[4296] 01 Oct 21:59:41.004 - DB 0: 3203 keys (3203 volatile) in 8192 slots HT.
[4296] 01 Oct 21:59:41.004 - 50 clients connected (0 slaves), 834546896 bytes in use
[4296] 01 Oct 21:59:46.473 - DB 0: 3208 keys (3208 volatile) in 8192 slots HT.
[4296] 01 Oct 21:59:46.473 - 50 clients connected (0 slaves), 834791096 bytes in use
[4296] 01 Oct 21:59:51.941 - DB 0: 3218 keys (3218 volatile) in 8192 slots HT.
[4296] 01 Oct 21:59:51.941 - 50 clients connected (0 slaves), 837611496 bytes in use
[4296] 01 Oct 21:59:57.410 - DB 0: 3220 keys (3220 volatile) in 8192 slots HT.
[4296] 01 Oct 21:59:57.410 - 50 clients connected (0 slaves), 839008576 bytes in use
[4296] 01 Oct 22:00:02.879 - DB 0: 3221 keys (3221 volatile) in 8192 slots HT.
[4296] 01 Oct 22:00:02.879 - 50 clients connected (0 slaves), 837853832 bytes in use
[4296] 01 Oct 22:00:08.347 - DB 0: 3224 keys (3224 volatile) in 8192 slots HT.
[4296] 01 Oct 22:00:08.347 - 50 clients connected (0 slaves), 838871328 bytes in use
[4296] 01 Oct 22:00:13.816 - DB 0: 3226 keys (3226 volatile) in 8192 slots HT.
[4296] 01 Oct 22:00:13.816 - 50 clients connected (0 slaves), 837981512 bytes in use
[4296] 01 Oct 22:00:19.285 - DB 0: 3225 keys (3225 volatile) in 8192 slots HT.
[4296] 01 Oct 22:00:19.285 - 50 clients connected (0 slaves), 838833320 bytes in use
[4296] 01 Oct 22:00:24.754 - DB 0: 3225 keys (3225 volatile) in 8192 slots HT.
[4296] 01 Oct 22:00:24.754 - 50 clients connected (0 slaves), 838727536 bytes in use
[4296] 01 Oct 22:00:30.223 - DB 0: 3218 keys (3218 volatile) in 8192 slots HT.
[4296] 01 Oct 22:00:30.223 - 50 clients connected (0 slaves), 836068976 bytes in use
[4296] 01 Oct 22:00:35.691 - DB 0: 3223 keys (3223 volatile) in 8192 slots HT.
[4296] 01 Oct 22:00:35.691 - 50 clients connected (0 slaves), 835290672 bytes in use
[4296] 01 Oct 22:00:41.160 - DB 0: 3232 keys (3232 volatile) in 8192 slots HT.
[4296] 01 Oct 22:00:41.160 - 50 clients connected (0 slaves), 837397344 bytes in use
[4296] 01 Oct 22:00:43.020 \* 10 changes in 300 seconds. Saving...
[4296] 01 Oct 22:00:43.082 \* Background saving started by pid 2900
[4296] 01 Oct 22:00:46.692 - DB 0: 3243 keys (3243 volatile) in 8192 slots HT.
[4296] 01 Oct 22:00:46.692 - 50 clients connected (0 slaves), 841203800 bytes in use
[4296] 01 Oct 22:00:51.504 # fork operation complete
[4296] 01 Oct 22:00:51.879 # EndForkOperation: 0x000001e7 - RejoinCOWPages: MapViewOfFileEx failed.: unknown error

[2112] 01 Oct 22:01:52.349 \* Redis 2.8.2103 (00000000/0) 64 bit, stand alone mode, port 20001, pid 2112 ready to start.
[2112] 01 Oct 22:01:52.349 # Server started, Redis version 2.8.2103
[2112] 01 Oct 22:01:52.380 - Accepted 10.101.25.63:57678
[2112] 01 Oct 22:01:52.380 - Accepted 10.101.25.63:57679
[2112] 01 Oct 22:01:52.395 - Accepted 10.101.10.91:61174
[2112] 01 Oct 22:01:52.411 - Accepted 10.101.10.91:61175
[2112] 01 Oct 22:01:52.427 - Accepted 192.0.2.79:57118
[2112] 01 Oct 22:01:52.427 - Accepted 192.0.2.79:57119
[2112] 01 Oct 22:01:52.458 - Client closed connection
[2112] 01 Oct 22:01:52.458 - Client closed connection
[2112] 01 Oct 22:01:52.770 - Accepted 10.101.28.197:63913
[2112] 01 Oct 22:01:52.786 - Accepted 10.101.28.197:63914
[2112] 01 Oct 22:01:52.802 - Client closed connection
[2112] 01 Oct 22:01:52.833 - Client closed connection
[2112] 01 Oct 22:01:52.864 - Accepted 192.0.2.115:57604
[2112] 01 Oct 22:01:52.864 - Accepted 192.0.2.115:57605
[2112] 01 Oct 22:01:52.895 - Client closed connection
[2112] 01 Oct 22:01:52.895 - Client closed connection
[2112] 01 Oct 22:01:53.427 - Accepted 192.0.2.79:57121
[2112] 01 Oct 22:01:53.427 - Accepted 192.0.2.79:57120
[2112] 01 Oct 22:01:53.442 - Client closed connection
[2112] 01 Oct 22:01:53.442 - Client closed connection
[2112] 01 Oct 22:01:53.770 - Accepted 10.101.28.197:63915
[2112] 01 Oct 22:01:53.770 - Accepted 10.101.28.197:63916
[2112] 01 Oct 22:01:53.802 - Client closed connection
[2112] 01 Oct 22:01:53.802 - Client closed connection
[2112] 01 Oct 22:01:53.895 - Accepted 192.0.2.115:57606
[2112] 01 Oct 22:01:53.895 - Accepted 192.0.2.115:57607
[2112] 01 Oct 22:01:53.927 - Client closed connection
[2112] 01 Oct 22:01:53.927 - Client closed connection
[2112] 01 Oct 22:01:54.427 - Accepted 192.0.2.79:57123
[2112] 01 Oct 22:01:54.427 - Accepted 192.0.2.79:57122
[2112] 01 Oct 22:01:54.442 - Client closed connection
[2112] 01 Oct 22:01:54.442 - Client closed connection
[2112] 01 Oct 22:01:54.771 - Accepted 10.101.28.197:63917
[2112] 01 Oct 22:01:54.771 - Accepted 10.101.28.197:63918
[2112] 01 Oct 22:01:54.786 - Client closed connection
[2112] 01 Oct 22:01:54.786 - Client closed connection
[2112] 01 Oct 22:01:54.864 - Accepted 192.0.2.115:57608
[2112] 01 Oct 22:01:54.864 - Accepted 192.0.2.115:57609
[2112] 01 Oct 22:01:54.896 - Client closed connection
[2112] 01 Oct 22:01:54.896 - Client closed connection

**Comment by enricogior** [comment] 2015-10-05 07:44
Hi @StefanPlizga 
the error code corresponds to ERROR_INVALID_ADDRESS.
When that type of error occurs, redis quits since it's an unrecoverable error, that's why there wasn't a crash report.
It's hard to tell what caused the invalid address error, it seems a system problem rather than a application bug. If the problem happens again, please run a ram and a disk check to make sure it's not hardware related.
Thank you.

**Comment by StefanPlizga** [comment] 2015-10-19 07:14
Hi @enricogior 
This issue happens sometimes. Machines hosting Redis are virtual machines, so disk and RAM should be OK within the virtual machine.
Is there a way to troubleshoot this issue and understand more what is causing it?
Thanks

**Comment by enricogior** [comment] 2015-10-19 07:39
Hi @StefanPlizga 
the error is caused by a system call failure. Unfortunately the failure doesn't report a detailed error.
Knowing what other programs are running on the same box may help, since one of the possible cause it's a race condition while mapping the address space.
Is there an antivirus software running on the box?

**Comment by StefanPlizga** [comment] 2015-10-19 08:02
Hi @enricogior 
Yes, there is an antivirus, however it is configured to exclude Redis folders and .RDB files from the scan.
Would Redis write files outside of its directory when doing fork operation, such as writing to %TEMP% folder?
Thanks

**Comment by enricogior** [comment] 2015-10-19 08:16
@StefanPlizga 
unless the default configuration is changed, the RedisQFork_*.dat file is created in a local app data folder. Instead of adding the local app data folder to the exclude list, I suggest to set the heapdir flag in the configuration file (e.g. `C:\RedisHeadDir`) and exclude it from the antivirus scan.

**Comment by StefanPlizga** [comment] 2015-10-19 08:31
Hi @enricogior 
Actually the heapdir is already configured for the Redis instance to a directory that is exluced from the AV.
Here is the full set of AV exclusions:
- All data (RDB, DAT, Redis executables...) is under C:\Redis
- Location C:\Redis is excluded from AV
- RDB extension is excluded from AV
- redis-server.exe process is excluded from AV

**Comment by enricogior** [comment] 2015-10-19 08:33
@StefanPlizga 
if you are using Windows Server 2012 or higher, I can provide a private build with a possible fix for the problem.

**Comment by StefanPlizga** [comment] 2015-10-19 08:36
@enricogior 
Yes please, we are using Windows Server 2012 R2. Let me know you to proceed.

**Comment by enricogior** [comment] 2015-10-19 08:37
@StefanPlizga 
I'm working on it, it should be ready shortly, I'll let you know when the build is ready.

**Comment by enricogior** [comment] 2015-10-19 11:48
@StefanPlizga 
the MSI and the zip files are available [here](http://1drv.ms/1MOMuJi).
MapViewOfFileEx is called in two different cases, the error report didn't indicate in which case it failed.
The fix is replacing the MapViewOfFileEx call only in one case, so I can't guarantee it will fix the problem but it's worhty running it anyway since it will help narrowing down the problem if it happens again.

**Comment by StefanPlizga** [comment] 2015-10-19 15:20
Thank you @enricogior 
I updated the build with this new one. Should I expect no bug anymore or just more information in the log file when the issue occurs?

**Comment by enricogior** [comment] 2015-10-19 15:23
@StefanPlizga 
I've removed the MapViewOfFileEx call in one place, if the bug was there you will not see the error anymore.
But there is still another place where MapViewOfFileEx is used and it may still cause the error, if it happens it will have the same log as before.

**Comment by StefanPlizga** [comment] 2015-11-12 10:58
Hi @enricogior 
FYI, since the fix, I did not encounter the issue anymore. Would you recommned me to stay with the private build for the moment or to go with public 2104 build? Is this change incorporated into it?
For my understanding, you said you removed the MapViewOfFileEx call in one place, does that mean this was not necessary for Redis to work correctly?
Thanks

**Comment by enricogior** [comment] 2015-11-12 13:18
Hi @StefanPlizga 
the fix is not in the public 2104 build, therefore I suggest you keep using the private build.
The fix took advantage of a new feature introduced with Windows Server 2012, it allows to avoid a MapViewOfFileEx call that is still required on previous Windows versions.
Given the positive feedback I will incorporate the fix in the next public build (later this month).
Thank you.

**Comment by prashant4github** [comment] 2015-12-11 11:04
Hi enricogior,
Is this bug fixed in latest version 3.0.500? We are using Redis version 2.8.2104 in PROD and we are also facing the same issue. Please reply.
Thanks.

**Comment by enricogior** [comment] 2015-12-11 15:34
Hi @prashant4github,
the fix for this issue will be included in 2.8.23 (that will be released in early January) and it solves the problem on Windows 8/Windows Server 2012 and later.
3.0.500 still uses MapViewOfFileEx but in a slightly different way, so I can't really say that is fixed since the initial conditions are different. We are planning to remove MapViewOfFileEx in 3.0.501 but only for Windows 10/Windows Server 2016.

**Comment by prashant4github** [comment] 2015-12-14 07:53
Hi @enricogior,
Thanks for providing quick reply. I will try to test 3.0.500 and see if that solves the problem. If 3.0.500 doesn't work, we will wait for public release of build 2.8.23.

Thanks a lot.

**Comment by prashant4github** [comment] 2016-01-19 14:39
Hi @enricogior,
Let us know when you plan to release "build 2.8.23" with above fixes for windows 8/ Windows server 2012. 
Thanks.

**Comment by prashant4github** [comment] 2016-01-19 14:44
Hi @enricogior,
We tested 3.0.500 on windows server 2012 and found that fix does not work for windows 8/ windows server 2012. Just wanted to share this information.
Thanks.

**Comment by enricogior** [comment] 2016-01-19 14:59
Hi @prashant4github 
we are currently testing 2.8.24, if all the tests pass we will release the build asap (at later at the beginning of next week).

Version 3.0 has a different architecture compared to 2.8, therefore the MapViewOfFileEx change we made in 2.8 is not yet present in 3.0 and it will work only on Windows 10 and Windows Server 2016.

**Comment by prashant4github** [comment] 2016-01-21 14:45
Hi @enricogior,
Thanks for the update. We will wait for the public release of build 2.8.24.
Thanks.

**Comment by enricogior** [comment] 2016-01-21 20:13
[Release v2.8.2400](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2400) fixes the issue.

**Closed as completed by enricogior** 2016-01-21 20:13 UTC
Labels: Solved

**Comment by xbiswajit** [comment] 2016-07-06 08:56
Has this issue being fixed in version "win-3.0.504" for Windows Server 2012?

**Comment by parvi81** [comment] 2016-11-28 14:54
I'm having this problem on Release 2.8.2402.
These are latest rows on log:

[4064] 25 Nov 10:45:08.594 * Background saving terminated with success
[4064] 25 Nov 10:47:11.881 * 10000 changes in 60 seconds. Saving...
[4064] 25 Nov 10:47:11.912 * Background saving started by pid 21376
[4064] 25 Nov 10:47:13.660 # fork operation complete
[4064] 25 Nov 10:47:13.956 # EndForkOperation: 0x000001e7 - RejoinCOWPages: MapViewOfFileEx failed.: unknown error
