### ISSUE TITLE
Redis on Windows Setup Wizard ended prematurely

### ISSUE THREAD

**Issue by howanu** [microsoftarchive/redis#313] opened 2015-09-11 22:22 UTC
Running Redis-x64-2.8.2103.msi yields the following response:

Redis on Windows Setup Wizard ended prematurely

Redis on Windows Setup Wizard ended prematurely because of an error. Your system has not been modified.To install this program at a later time, run Setup Wizard again. Click the Finish button to exit the Setup Wizard.

Environment:
Windows Server 2008 R2 Enterprise SP 1 64 bit

From the Windows Event Viewer:
Windows Installer installed the product. 
Product Name: Redis on WIndows.
Product Version: 2.8.2103
Product Language: 1033
Manufacturer: MSOpenTech.
Installation success or error status: 1603

The site https://support.microsoft.com/en-us/kb/834484 reports that there are three possible reasons for the error, but none of the three seems to apply. 

I will continue to troubleshoot, but has anyone seen a similar problem upon installation?

**Comment by enricogior** [comment] 2015-09-11 23:34
Hi @howanu 
in the Event log is there any entry where the source is 'redis'?
During the installation did you use the default settings?

**Comment by howanu** [comment] 2015-09-12 00:19
Thank you for the help! Unfortunately, I did use default settings (just running the .msi file, and clicking "Run").

There is only one other event, whose source is also MsiInstaller. Its Event ID is 11708 and it reads only "Product: Redis on Windows -- Installation failed."

**Comment by enricogior** [comment] 2015-09-12 01:12
@howanu 
try setting the memory limits to 100MB for max memory and 150MB for maxheap in the 5th dialog during the MSI installation.
![msi](https://cloud.githubusercontent.com/assets/3206696/9829228/18b837fc-58fc-11e5-897e-4153d49b5cec.png)

**Comment by howanu** [comment] 2015-09-12 02:15
Thanks @enricogior . I probably should have mentioned that I don't even see the second dialog - as soon as I hit "Run", I get the error screen, and my only choice is the "Finish".button.

**Comment by enricogior** [comment] 2015-09-12 02:17
@howanu 
since we made a change in the MSI in 2.8.2103, it may be a regression, can you try to install 2.8.2102 to verify if it works?
Thank you.

**Comment by howanu** [comment] 2015-09-12 02:25
Hi @enricogior - luckily it's not a problem with the 2103 MSI change. Both versions 2102 and 2011 give the same error for me.

**Comment by enricogior** [comment] 2015-09-12 03:23
@howanu 
I will try to prepare a private MSI with extended debug info.
In the meantime you can download the zip file as an alternative to the MSI.

**Comment by Coop197823** [comment] 2015-10-18 22:48
Unfortunately, I have run into this same issue with 3.0.300-alpha3 on windows server 2008 r2.  Any workaround to get this up and running?

**Comment by howanu** [comment] 2015-10-19 12:55
I never succeeded in installing through MSI, but I was able to install using the zip download. Following the instructions in the Windows Service Documentation that comes in the zip, I used redis-server --service-install redis.windows.conf --loglevel verbose to install the redis service.

**Comment by enricogior** [comment] 2015-10-19 12:58
@howanu 
what .Net versions are installed on the machine?
You can use the following command to list them all `dir %WINDIR%\Microsoft.Net\Framework\v* /O:-N /B`.
Thank you.

**Comment by Coop197823** [comment] 2015-10-19 13:09
Thanks you for your help!, I created a new thread for the issue, but you are right, that was the issue!  Thanks!

**Comment by enricogior** [comment] 2015-11-16 19:11
@howanu 
I'm closing the issue.
Feel free to reopen it if needed.
Thanks.

**Closed as completed by enricogior** 2015-11-16 19:11 UTC

**Comment by Coop197823** [comment] 2015-11-16 19:16
No problem, I got the system up and running and it is working beautifully!!

Thanks again!
Clinton

**Comment by howanu** [comment] 2015-11-16 19:22
Working for me as well … thanks, Enrico.

**Comment by HakamFostok** [comment] 2019-12-18 13:26
Restarting Windows solved the problem
