### ISSUE TITLE
redis server crash

### ISSUE THREAD

**Issue by husttb** [microsoftarchive/redis#56] opened 2013-08-13 03:19 UTC
[1936] 12 Aug 11:09:03.375 \* DB saved on disk
[1936] 12 Aug 11:09:03.381 \* Background saving terminated with success
[1936] 12 Aug 11:09:03.383 \* cowBkgdSaveReset deleting 5 SDS and 7060 obj items
[1936] 12 Aug 11:09:28.803 # Out Of Memory allocating 743763 bytes!

the memory is enough and the memory of redis server is only 110MB

**Comment by clca** [comment] 2013-08-13 16:30
Can you share more details on how we can repro this problem?
Type of operations, # clients, ....

**Comment by husttb** [comment] 2013-08-14 01:18
[1936] 12 Aug 11:07:56.521 \* elapsed COW DB expires time 0
[1936] 12 Aug 11:07:57.110 \* elapsed COW DB expires time 0
[1936] 12 Aug 11:07:59.592 \* DB saved on disk
[1936] 12 Aug 11:07:59.598 \* Background saving terminated with success
[1936] 12 Aug 11:07:59.600 \* cowBkgdSaveReset deleting 48 SDS and 9297 obj items
[1936] 12 Aug 11:09:00.004 \* 10000 changes in 60 seconds. Saving...
[1936] 12 Aug 11:09:00.004 \* cowBkgdSaveReset deleting 0 SDS and 0 obj items
[1936] 12 Aug 11:09:00.406 \* elapsed COW DB expires time 0
[1936] 12 Aug 11:09:01.646 \* elapsed COW DB expires time 0
[1936] 12 Aug 11:09:03.375 \* DB saved on disk
[1936] 12 Aug 11:09:03.381 \* Background saving terminated with success
[1936] 12 Aug 11:09:03.383 \* cowBkgdSaveReset deleting 5 SDS and 7060 obj items
[1936] 12 Aug 11:09:28.803 # Out Of Memory allocating 743763 bytes!
[1936] 12 Aug 11:09:28.803 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[1936] 12 Aug 11:09:28.804 # ------------------------------------------------
[1936] 12 Aug 11:09:28.804 # !!! Software Failure. Press left mouse button to continue
[1936] 12 Aug 11:09:28.804 # Guru Meditation: "OOM" #..\src\redis.c:2723
[1936] 12 Aug 11:09:28.805 # ------------------------------------------------

**Comment by jepickett** [comment] 2013-09-13 22:08
How can I replicate this problem? Does this occur on a regular basis, or is it a once in a "blue moon" kind of thing? Are you using the 32-bit or 64-bit version of redis-server.exe? What OS version are you using?

**Comment by BeatriceOltean** [comment] 2013-09-16 22:19
Looking for configuration that reproduce this bug

**Comment by jepickett** [comment] 2014-02-12 17:59
This is likely fixed in 2.6.14 with our new qfork implementation.

**Comment by jepickett** [comment] 2014-04-02 00:52
2.6.14 and 2.8.4 have been released. The signed binaries are available via NuGet and Chocolatey. The failures were due to the previous workaround for fork().

**Closed as completed by jepickett** 2014-04-02 00:52 UTC
Labels: Bug
