### ISSUE TITLE
2.8.9 & 2.8.12 - crash under single client load test

### ISSUE THREAD

**Issue by d15p0-140328** [microsoftarchive/redis#161] opened 2014-08-13 18:16 UTC
typically crashes after < 1m iterations

redis-server --appendonly yes
redis-server --port 6380 --slaveof 127.0.0.1 6379 --appendonly yes --appendfsync everysec

(version 2.6 ran fine overnight, ~85m iterations)

```
    while(i<Integer.MAX_VALUE){
        ++i;
        String key="key"+1;
        String val="val"+i;
        set(dbNum,key,val);
        val=get(dbNum,key);
        System.out.println("got val: "+val);
    }
```

protected static String get(RedisConnArgs rca, int dbNum, String keyName){
    Jedis jdb=null;
    boolean broken=false;
    try {
        jdb=RedisPool.getResource( rca ); //new RedisConnArgs(RedisPool.DEFAULT_HOST,RedisPool.DEFAULT_PORT) );
        if(jdb.getDB()!=dbNum)
            jdb.select(dbNum);
        String val = jdb.get(keyName);
        return val;
    } catch (JedisConnectionException e) {
        e.printStackTrace();
        broken=true;
    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        if(jdb!=null){
            RedisPool.returnResource(jdb,broken);
        }
    }
    return null;
}

protected static String get(Jedis jdb, String keyName){
    boolean broken=false;
    try {
        String val = jdb.get(keyName);
        return val;
    } catch (JedisConnectionException e) {
        e.printStackTrace();
        broken=true;
    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        if(jdb!=null){
            RedisPool.returnResource(jdb,broken);
        }
    }
    return null;
}

Problem signature:
  Problem Event Name:   BEX64
  Application Name: redis-server.exe
  Application Version:  0.0.0.0
  Application Timestamp:    53dad9a5
  Fault Module Name:    redis-server.exe
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   53dad9a5
  Exception Offset: 00000000000aa080
  Exception Code:   c0000409
  Exception Data:   0000000000000007
  OS Version:   6.3.9600.2.0.0.256.48
  Locale ID:    1033
  Additional Information 1: f76e
  Additional Information 2: f76e8c50513697783514f11fc6e05eba
  Additional Information 3: 4126
  Additional Information 4: 4126887aa28cd2a82307a74ba3e42f29

**Comment by d15p0-140328** [comment] 2014-08-13 18:25
forgot to post the set:

```
protected static boolean set(RedisConnArgs rca, int dbNum, String key, String value){
    Jedis jdb=null;
    boolean broken=false;
    try {
        jdb=RedisPool.getResource( rca ); //new RedisConnArgs(RedisPool.DEFAULT_HOST,RedisPool.DEFAULT_PORT) );
        if(jdb.getDB()!=dbNum)
            jdb.select(dbNum);
        jdb.set(key, value);
        return true;
    } catch (JedisConnectionException e) {
        e.printStackTrace();
        broken=true;
    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        if(jdb!=null){
            RedisPool.returnResource(jdb,broken);
        }
    }
    return false;
}
```

**Comment by d15p0-140328** [comment] 2014-08-13 21:19
I just updated jedis from 2.1.0 to 2.5.1 and it seems happier; I'll let it run overnight and report back tomorrow

**Comment by d15p0-140328** [comment] 2014-08-13 21:26
unfortunately I didn't have to wait long for an answer...

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: redis-server.exe
  Application Version:  0.0.0.0
  Application Timestamp:    53dad9a5
  Fault Module Name:    redis-server.exe
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   53dad9a5
  Exception Code:   c0000005
  Exception Offset: 0000000000073d2c
  OS Version:   6.3.9600.2.0.0.256.48
  Locale ID:    1033
  Additional Information 1: 5f66
  Additional Information 2: 5f66463dc2cc597fd3d5720ade738dda
  Additional Information 3: e440
  Additional Information 4: e4402fe2e0c10aa984260dd4c1733096

**Comment by jepickett** [comment] 2014-08-13 23:50
I am seeing the problem. It looks like a heap corruption issue when appendonly is yes. It may take a couple of days to nail this down and get a fix ready.

**Comment by d15p0-140328** [comment] 2014-08-14 17:19
cool; thx for the quick response; heap problems can be a b!7ch

**Comment by jepickett** [comment] 2014-08-15 02:42
Fixed in commit 36f30412b52f661f2736ddc5411c9c33fddee5fb. Let me know if this works in your environment.

**Comment by d15p0-140328** [comment] 2014-08-15 19:44
well, I'm currently @ 15m iterations; previously it would crash < 1m iterations, so I think we're good.
thx for the fix!

**Comment by nmehlei** [comment] 2014-08-25 16:15
Today my redis-server instance crashed with the same exception code (0xc0000409) as was mentioned in the first post, could this be related? If it is, then the problem is not fixed yet since I am already running the latest binary including the fix from commit 36f3041. 

Data:
Application Error Faulting application name: redis-server.exe, version: 0.0.0.0, time stamp: 0x53ed7150
Faulting module name: redis-server.exe, version: 0.0.0.0, time stamp: 0x53ed7150
Exception code: 0xc0000409
Fault offset: 0x00000000000aa1c0
Faulting process id: 0xed4
Faulting application start time: 0x01cfbc8109d8ff8a
Faulting application path: E:\view-storage-bin\redis-server.exe
Faulting module path: E:\view-storage-bin\redis-server.exe
Report Id: d733496c-2c64-11e4-80bd-00155d49d8e4
Faulting package full name: 
Faulting package-relative application ID:

**Comment by jepickett** [comment] 2014-08-25 19:40
Can you reproduce the problem? The 0xC0000409 message just indicates that an unhandled exception was thown in from C++ code. What error is in the event log at the time of the crash?

**Comment by nmehlei** [comment] 2014-08-26 10:22
Did only occur a single time over the last few days, but we had and have trouble with redis (unknown if server- or client-based) for some time so it's possible that this is the root cause, but thats a wild guess.
redis-server (at least its service wrapper nssm) exited with return code 3221226505, followed by:

0 1001 EVENTLOG_INFORMATION_TYPE #3251 Windows Error Reporting Fault bucket , type 0
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: redis-server.exe
P2: 0.0.0.0
P3: 53ed7150
P4: redis-server.exe
P5: 0.0.0.0
P6: 53ed7150
P7: 00000000000aa1c0
P8: c0000409
P9: 0000000000000007
P10: 

Attached files:
C:\Windows\Temp\WER5F62.tmp.appcompat.txt
C:\Windows\Temp\WER60DA.tmp.WERInternalMetadata.xml
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_redis-server.exe_bbcf1a2aa24cb789e1a857f9ebb7bd10a92bc7f_a3d0af17_cab_296861b3\memory.hdmp
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_redis-server.exe_bbcf1a2aa24cb789e1a857f9ebb7bd10a92bc7f_a3d0af17_cab_296861b3\triagedump.dmp

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_redis-server.exe_bbcf1a2aa24cb789e1a857f9ebb7bd10a92bc7f_a3d0af17_cab_296861b3

Analysis symbol: 
Rechecking for solution: 0
Report Id: d733496c-2c64-11e4-80bd-00155d49d8e4
Report Status: 4
Hashed bucket:

Hope this helps a bit.

**Comment by jepickett** [comment] 2014-08-26 22:52
I would also like to look at the events in your application log. Please place all the files in a location where I can get to them (OneDrive, etc.). They will not make it through email.

**Comment by nmehlei** [comment] 2014-09-09 12:05
I just sent you an email containing the application log file extract of a newer crash. Curiously, just following redis's crash, Azure's AntiMalware (Endpoint Protection) agent seems to have crashes aswell. I'd guess those are related, maybe the AntiMalware agent somehow interferes with the memory-mapped file or something?

**Comment by jepickett** [comment] 2014-09-10 02:44
The app log says that there is a dump at "C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_redis-server.exe_5f1b474398119ef81262867ab35b8eb0ea91_a3d0af17_cab_06668776\triagedump.dmp". Can you find this file and upload it?

**Comment by nmehlei** [comment] 2014-09-10 08:24
Sure, I sent you the url for the file via email

**Comment by jepickett** [comment] 2014-09-11 21:17
The dump is a minidump, so it does not contain any memory information. All I have is a call stack. The stack looks like:

```
DbgID ThreadID     User Kernel
0     520 (0n1312)    0      0

 # Child-SP         Return           Call Site                                  Info                                            Source
 0 000000000013e248 00007ffe36db5bc8 ntdll!ZwGetContextThread+0xa                                                               
 1 000000000013e250 aaaaaaaaaaaaaaaa ntdll!RtlpFindUnicodeStringInSection+0x138                                                 
 2 000000000013e320 aaaaaaaaaaaaaaaa 0xaaaaaaaaaaaaaaaa                                                                         
 3 000000000013e328 aaaaaaaaaaaaaaaa 0xaaaaaaaaaaaaaaaa                                                                         
 4 000000000013e330 aaaaaaaaaaaaaaaa 0xaaaaaaaaaaaaaaaa                                                                         
 5 000000000013e338 00007ffe36e0f2d9 0xaaaaaaaaaaaaaaaa                                                                         
 6 000000000013e340 00007ffe36e0f09c ntdll!PsspSampleCounters+0x55                                                              
 7 000000000013e3a0 00007ffe366540cb ntdll!PssNtCaptureSnapshot+0x290                                                           
 8 000000000013e490 00007ffe36653e6f kernel32!WerpReportFaultInternal+0x1fb                                                     
 9 000000000013ea00 00007ffe342ada53 kernel32!WerpReportFault+0x83                                                              
 a 000000000013ea30 00007ffe36e3b1d4 KERNELBASE!UnhandledExceptionFilter+0x233                                                  
 b (Inline)         ---------------- ntdll!RtlpThreadExceptionFilter+0x23                                                       
 c 000000000013eb20 00007ffe36e1c92f ntdll!RtlUserThreadStart$filt$0+0x34                                                       
 d 000000000013eb50 00007ffe36e2d82d ntdll!__C_specific_handler+0x87                                                            
 e 000000000013ebc0 00007ffe36dd916b ntdll!RtlpExecuteHandlerForException+0xd                                                   
 f 000000000013ebf0 00007ffe36e2c9ee ntdll!RtlDispatchException+0x19b           Exception Code: aaaaaaaa Context Record: 13f2c0 
10 000000000013f2c0 000000014003291a ntdll!KiUserExceptionDispatch+0x2e                                                         
11 000000000013f880 aaaaaaaaaaaaaaaa redis_server!processCommand+0x20a                                                          c:\src\redis\2.8\src\redis.c @ 2132
12 000000000013f888 00000001400f3910 0xaaaaaaaaaaaaaaaa                                                                         
13 000000000013f890 aaaaaaaaaaaaaaaa redis_server!`string'                                                                      open start of function
14 000000000013f898 0000000000000000 0xaaaaaaaaaaaaaaaa 
```

This looks like a redisPanic() exception stack. From the call stack it looks like we are in the midst of redis.c in processCommand() at the addReply() call:

``` C
    /* Don't accept write commands if there are problems persisting on disk
     * and if this is a master instance. */
    if (((server.stop_writes_on_bgsave_err &&
          server.saveparamslen > 0 &&
          server.lastbgsave_status == REDIS_ERR) ||
          server.aof_last_write_status == REDIS_ERR) &&
        server.masterhost == NULL &&
        (c->cmd->flags & REDIS_CMD_WRITE ||
         c->cmd->proc == pingCommand))
    {
        flagTransaction(c);
        if (server.aof_last_write_status == REDIS_OK)
            addReply(c, shared.bgsaveerr);
        else
            addReplySds(c,
                sdscatprintf(sdsempty(),
                "-MISCONF Errors writing to the AOF file: %s\r\n",
                strerror(server.aof_last_write_errno)));
        return REDIS_OK;
    }
```

In addReply(), redisPanic() can be called at the end of the function:

``` C
    } else {
        redisPanic("Wrong obj->encoding in addReply()");
    }
}
```

So my guess is that background persistence has failed, and somehow this is leading to a very bad state in Redis. 

Since this looks like a new issue, I will close this one and open up another for us to work on.

**Closed as completed by jepickett** 2014-09-11 21:17 UTC

**Comment by jepickett** [comment] 2014-09-11 21:26
Continuing with new issue in 167
