### ISSUE TITLE
Redis-Server don't release socket

### ISSUE THREAD

**Issue by dragzhb** [microsoftarchive/redis#8] opened 2012-06-30 13:43 UTC
I found Redis-Server don't release socket.

When I open a redis-cli and closed it, but Redis-Server still show that the connection is alive.

I have tested in redis-2.4.5-win32-win64.zip (https://github.com/dmajkic/redis/downloads), this version of  Redis-Server can release socket.

**Comment by HenryRawas** [comment] 2012-07-02 21:27
Can you provide more information? When I try this I see the server log a message that the connection is closed (see below). Also if I put a break at the closesocket call the breakpoint is hit.
[7328] 02 Jul 14:25:00 - 1 clients connected (0 slaves), 6212564 bytes in use
[7328] 02 Jul 14:25:03 - Client closed connection
[7328] 02 Jul 14:25:05 - DB 0: 3 keys (0 volatile) in 4 slots HT.
[7328] 02 Jul 14:25:05 - 0 clients connected (0 slaves), 6204776 bytes in use

**Comment by dragzhb** [comment] 2012-07-03 02:24
I attached the error picture to your email.

**Comment by dragzhb** [comment] 2012-07-03 02:27
Hi,
The attachement is the error picture, I used redis on Windows XP

---

 发件人： Henry Rawas reply@reply.github.com
收件人： dragzhb dragzhb@yahoo.com.cn 
发送日期： 2012年7月3日, 星期二, 上午 5:27
主题: Re: [redis] Redis-Server don't release socket (#8)

Can you provide more information? When I try this I see the server log a message that the connection is closed (see below). Also if I put a break at the closesocket call the breakpoint is hit.
[7328] 02 Jul 14:25:00 - 1 clients connected (0 slaves), 6212564 bytes in use
[7328] 02 Jul 14:25:03 - Client closed connection
[7328] 02 Jul 14:25:05 - DB 0: 3 keys (0 volatile) in 4 slots HT.
[7328] 02 Jul 14:25:05 - 0 clients connected (0 slaves), 6204776 bytes in use

---

**Comment by dragzhb** [comment] 2012-07-03 02:35
# client:

D:\redisbin>redis-cli.exe
redis 127.0.0.1:6379> quit

D:\redisbin>redis-cli.exe
redis 127.0.0.1:6379> quit

D:\redisbin>redis-cli.exe
redis 127.0.0.1:6379> quit

D:\redisbin>redis-cli.exe

# redis 127.0.0.1:6379> quit

# server:

D:\redisbin>redis-server.exe
[2472] 03 Jul 10:30:06 # Warning: no config file specified, using the default config. In order to specify a config
redis-server /path/to/redis.conf'
[2472] 03 Jul 10:30:06 # Warning: 32 bit instance detected but no memory limit set. Setting 3.5 GB maxmemory limit
iction' policy now.
[2472] 03 Jul 10:30:06 \* cowInit
[2472] 03 Jul 10:30:06 \* Server started, Redis version 2.4.11
[2472] 03 Jul 10:30:06 \* The server is now ready to accept connections on port 6379
[2472] 03 Jul 10:30:06 - 0 clients connected (0 slaves), 444100 bytes in use
[2472] 03 Jul 10:30:11 - 0 clients connected (0 slaves), 444100 bytes in use
[2472] 03 Jul 10:30:17 - 0 clients connected (0 slaves), 444100 bytes in use
[2472] 03 Jul 10:30:22 - 0 clients connected (0 slaves), 444100 bytes in use
[2472] 03 Jul 10:30:25 - Accepted 127.0.0.1:2283
[2472] 03 Jul 10:30:28 - 1 clients connected (0 slaves), 452308 bytes in use
[2472] 03 Jul 10:30:30 - Accepted 127.0.0.1:2284
[2472] 03 Jul 10:30:33 - 2 clients connected (0 slaves), 460516 bytes in use
[2472] 03 Jul 10:30:37 - Accepted 127.0.0.1:2285
[2472] 03 Jul 10:30:39 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:30:44 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:30:50 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:30:55 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:31:01 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:31:06 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:31:12 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:31:17 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:31:22 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:31:28 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:31:33 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:31:39 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:31:44 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:31:50 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:31:55 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:32:01 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:32:06 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:32:12 - 3 clients connected (0 slaves), 468724 bytes in use
[2472] 03 Jul 10:32:17 - Accepted 127.0.0.1:2298
[2472] 03 Jul 10:32:17 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:32:23 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:32:28 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:32:34 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:32:39 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:32:45 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:32:50 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:32:55 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:33:01 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:33:06 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:33:12 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:33:17 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:33:23 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:33:28 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:33:34 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:33:39 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:33:45 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:33:50 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:33:56 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:34:01 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:34:07 - 4 clients connected (0 slaves), 476932 bytes in use
[2472] 03 Jul 10:34:12 - 4 clients connected (0 slaves), 476932 bytes in use

# ^C

**Comment by clca** [comment] 2012-07-10 21:20
The issue is fixed now with the latest [commit](https://github.com/MSOpenTech/redis/commit/138eb257198b0d9b91db0957dac560689b05e362).

**Closed as completed by clca** 2012-07-10 21:20 UTC
