### ISSUE TITLE
Service crash

### ISSUE THREAD

**Issue by rogerrong** [microsoftarchive/redis#260] opened 2015-06-30 21:34 UTC
Version 2.8.21.

The Redis windows service crashed after running for about 15 hours.

Following is the content at the end of the log file:

...
[5956] 30 Jun 01:14:30.413 - 4 clients connected (0 slaves), 4425120 bytes in use
[5956] 30 Jun 01:14:36.669 - DB 0: 3 keys (0 volatile) in 4 slots HT.
[5956] 30 Jun 01:14:36.669 - 4 clients connected (0 slaves), 4392368 bytes in use
[5956] 30 Jun 01:14:42.847 - DB 0: 3 keys (0 volatile) in 4 slots HT.
[5956] 30 Jun 01:14:42.862 - 4 clients connected (0 slaves), 4425848 bytes in use
[5956] 30 Jun 01:14:51.099 - Reading from client: An existing connection was forcibly closed by the remote host.
[5956] 30 Jun 01:14:51.973 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[5956] 30 Jun 01:14:51.973 # --- EXCEPTION_ACCESS_VIOLATION
[5956] 30 Jun 01:14:51.973 # --- INFO OUTPUT

**Comment by VevodaUlath** [comment] 2015-07-01 04:38
Same happened here yesterday, same version, couldn't find any useful error log.

**Comment by enricogior** [comment] 2015-07-01 07:22
@VevodaUlath, 
is redis-server running as a Windows service?

@rogerrong, @VevodaUlath, 
The fact that the stack trace is not present in the log is caused by failing to load the symbols, can you please check if the redis-server.pdb file is present in the folder where redis-server.exe is installed?
Can you also check the beginning of the log file for an error message containing "Failed to initialize process symbols"?
Thank you.

**Comment by rogerrong** [comment] 2015-07-01 07:47
Yes, it is a windows service running on Windows Server 2012.

The redis-server.pdb file does exist in the same folder where the redis-server.exe is installed. However, there is no error message containing "Failed to initialize process symbols". Following is the beginning of the error log:

[5956] 29 Jun 21:48:57.517 # Server started, Redis version 2.8.21
[5956] 29 Jun 21:48:57.517 \* The server is now ready to accept connections on port 6379
[5956] 29 Jun 21:48:57.530 - 0 clients connected (0 slaves), 4311448 bytes in use
[5956] 29 Jun 21:48:57.779 - Accepted 127.0.0.1:62605
[5956] 29 Jun 21:48:57.779 - Accepted 127.0.0.1:62604
[5956] 29 Jun 21:49:03.037 - DB 0: 3 keys (0 volatile) in 4 slots HT.
[5956] 29 Jun 21:49:03.037 - 2 clients connected (0 slaves), 4351872 bytes in use
[5956] 29 Jun 21:49:08.497 - DB 0: 3 keys (0 volatile) in 4 slots HT.
[5956] 29 Jun 21:49:08.497 - 2 clients connected (0 slaves), 4351872 bytes in use
[5956] 29 Jun 21:49:13.957 - DB 0: 3 keys (0 volatile) in 4 slots HT.
[5956] 29 Jun 21:49:13.957 - 2 clients connected (0 slaves), 4384656 bytes in use
[5956] 29 Jun 21:49:19.464 - DB 0: 3 keys (0 volatile) in 4 slots HT.
[5956] 29 Jun 21:49:19.464 - 2 clients connected (0 slaves), 4351872 bytes in use
[5956] 29 Jun 21:49:24.924 - DB 0: 3 keys (0 volatile) in 4 slots HT.
[5956] 29 Jun 21:49:24.924 - 2 clients connected (0 slaves), 4351872 bytes in use
...

![redis](https://cloud.githubusercontent.com/assets/13125156/8449923/e2890c02-2029-11e5-8de8-73286c252a04.png)

**Comment by enricogior** [comment] 2015-07-01 07:50
@rogerrong, 
thanks for the info, I'll investigate why the stack trace hasn't been logged, that is not supposed to happen unless the symbols can't be loaded.
Can you also please check if a Windows mini or full crash dump has been created?

**Comment by rogerrong** [comment] 2015-07-01 07:57
Any idea which folder the crash dump file created in? 

Just checked the Windows event log which contains the following error message:

Log Name:      Application
Source:        Application Error
Date:          6/30/2015 1:14:54 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      RogerTest
Description:
Faulting application name: redis-server.exe, version: 0.0.0.0, time stamp: 0x558b1f29
Faulting module name: redis-server.exe, version: 0.0.0.0, time stamp: 0x558b1f29
Exception code: 0xc0000005
Fault offset: 0x0000000000086a34
Faulting process id: 0x1744
Faulting application start time: 0x01d0b2f012ef43d6
Faulting application path: C:\redis-x64-2.8.21\redis-server.exe
Faulting module path: C:\redis-x64-2.8.21\redis-server.exe
Report Id: 161cfef3-1f00-11e5-93eb-000c2994897c
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-06-30T08:14:54.000000000Z" />
    <EventRecordID>145076</EventRecordID>
    <Channel>Application</Channel>
    <Computer>RogerTest</Computer>
    <Security />
  </System>
  <EventData>
    <Data>redis-server.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>558b1f29</Data>
    <Data>redis-server.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>558b1f29</Data>
    <Data>c0000005</Data>
    <Data>0000000000086a34</Data>
    <Data>1744</Data>
    <Data>01d0b2f012ef43d6</Data>
    <Data>C:\redis-x64-2.8.21\redis-server.exe</Data>
    <Data>C:\redis-x64-2.8.21\redis-server.exe</Data>
    <Data>161cfef3-1f00-11e5-93eb-000c2994897c</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by enricogior** [comment] 2015-07-01 09:15
@rogerrong 
please follow these instructions to enable the crush dump report:
https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx

I suggest to create a dump folder and explicity set the path without using %LOCALAPPDATA%
Here is an example of how the registry key should look like:
![crushdump](https://cloud.githubusercontent.com/assets/3206696/8451246/2bd56614-1fe2-11e5-866a-7deed045788c.png)

**Comment by rogerrong** [comment] 2015-07-01 09:38
The crash dump report is enabled, waiting for the next crash...

![crashdump](https://cloud.githubusercontent.com/assets/13125156/8451711/52d14a38-2039-11e5-88fc-4fbfcdc956ba.png)

**Comment by bruceliu2008** [comment] 2015-07-03 09:43
Again, this version can't give me any confidence to upgrade.

**Comment by enricogior** [comment] 2015-07-15 15:34
@rogerrong, @VevodaUlath,
a new release is available, it addresses several issues including a crash that has similar symptoms to the one you reported. I"m closing this issue, but please reopen it in case you still run into this problem.
Thank you.

The new 2.8.2101 release is available [here](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2101).
This is an incremental release from 2.8.21 containing only fixes for Windows-specific bugs.  

Note: we don't have yet a date for the availability of the new release through the nuget/chocolatey package managers.

**Closed as completed by enricogior** 2015-07-15 15:34 UTC
Labels: Bug, P1
