### ISSUE TITLE
MSI installer - Service 'Redis' failed to start

### ISSUE THREAD

**Issue by ioleo** [microsoftarchive/redis#403] opened 2016-02-06 14:55 UTC
I've tried both 2.8 and 3.0 installers. I have lowered the account control (to not ask when apps want to change something) to no avail. The only way I could use is installing from zip and useing the redis-server.exe to start services via command line.

**Comment by enricogior** [comment] 2016-02-08 12:56
Hi @loostro 
can you please describe in which stage of the installation the error occurs.
Thank you.

**Comment by ioleo** [comment] 2016-02-08 13:02
Attached screenshot 

![MSI Redis installation failed to start service](https://cloud.githubusercontent.com/assets/1419884/12886302/806cf7da-ce6c-11e5-89f0-5b8c9b5c6f1d.PNG)

**Comment by ioleo** [comment] 2016-02-08 13:04
@enricogior This was a screenshot from the 2.8 installer, but I get exacly the same with 3.0 (the same error message, at the same stage during installation). 

The process hangs for about 30-60secs in `Starting services` step, then pops up the error message on the right.

**Comment by enricogior** [comment] 2016-02-08 13:19
@loostro 
on what Windows version?

**Comment by ioleo** [comment] 2016-02-08 13:22
@enricogior Windows 10 Home, 64bit, PL

**Comment by enricogior** [comment] 2016-02-08 13:46
@loostro 
I don't have a Windows 10 Home to test, I tried on a Windows 10 Pro and it worked without problem.
Try to check the Event Viewer and the MSI log to find any useful information on the error (to create the MSI log: msiexec /i "C:\temp\Redis-x64-3.0.501.msi" /L*V "C:\temp\redis-msi.log").

**Comment by manuelbieh** [comment] 2016-02-10 11:12
Same problem here with Windows 10 Professional. Same error on the same stage in the setup process.

**Comment by manuelbieh** [comment] 2016-02-10 11:26
Ok, worked for me:
- download the zipfile instead
- unzip
- start command shell as administrator
- `redis-server --service-install`
- `redis-server --service-start`

**Comment by ioleo** [comment] 2016-02-10 12:18
The zip also works for me. Still, it would be nice if MSI installer worked.

**Comment by enricogior** [comment] 2016-02-10 23:52
@manuelbieh 
can you please provide the MSI log, in order to identify the cause of the failure.
Thank you.

**Comment by panyamin** [comment] 2016-02-13 20:45
Hello,

Here's the MSI log: https://gist.github.com/panyamin/fcc0c9bdb4933eb94cd3

**Comment by lhecker** [comment] 2016-02-14 13:11
BTW: If you try to start the service manually while the "Retry"-dialog is still open it will fail with

> Error 1068: The dependency service or group failed to start

The Redis service does not have any dependencies though so I'm a bit confused about the meaning of this...

**Comment by enricogior** [comment] 2016-02-15 08:51
Hi @panyamin 
thanks for the log, it confirms the error is caused by the service non starting, can you please confirm the Windows version?
Could you also please check the event log (Event Viewer -> Windows Logs -> Application) for entries reporting Redis errors?
Thank you.

**Comment by enricogior** [comment] 2016-02-15 08:52
Hi @lhecker 
that scenario is not supported, therefore I wouldn't worry about the error message.
Can you please report the Windows version you are using?
Thank you.

**Comment by lhecker** [comment] 2016-02-15 10:02
@enricogior Windows 10 Pro 64 Bit, Version 1511 (Build 10586.104) and no relevant modifications to the system I could think of...

**Comment by panyamin** [comment] 2016-02-15 10:38
Also Windows 10 Pro 64 bit, Version 1511 - Build10586.104
I'll check tonight if there are something in logs.

**Comment by enricogior** [comment] 2016-02-15 15:20
@loostro, @manuelbieh, @panyamin, @lhecker 
I haven't been able to reproduce the problem so far using Windows 10 Pro and Windows 10 Enterprise with local and Microsoft accounts.
Can you please let me know more about the configuration you are using? Local account, Microsoft account or domain account? The user is a machine admin?
Thank you.

**Comment by manuelbieh** [comment] 2016-02-15 15:23
I was using a local account on Win 10 Pro. My account type is administrator and I also ran the installer as such. 

Let me know if you need more info.

//edit:
UAC Settings were set to "never notify".

**Comment by panyamin** [comment] 2016-02-15 20:56
Log in Event Viewer:
`Product: Redis on Windows -- Error 1920. Service 'Redis' (Redis) failed to start. Verify that you have sufficient privileges to start system services.`

**Comment by enricogior** [comment] 2016-02-15 21:06
Thanks, clearly it doesn't add more info, if there aren't other Redis entries in the Event log it may mean that the service is actually not even invoked in the first place.

**Comment by seriouz** [comment] 2016-02-15 21:08
I have the same problem on a Windows Server 2008 R2 with the MSI package.

**Comment by enricogior** [comment] 2016-02-15 21:11
@seriouz
on Windows Server 2008 it may be a different issue, make sure you have the .Net framework 4.5 installed.

**Comment by enricogior** [comment] 2016-02-18 18:12
@loostro @manuelbieh @panyamin @lhecker 
I created an MSI (available [here](http://1drv.ms/1OijQMj)) with some extra event log info, it may help identify the cause of the problem.
After the installation failure you need to check the Event log for entries with **source** equal to **redis**.
Thank you.

**Comment by lhecker** [comment] 2016-02-22 15:15
Hey @enricogior! I'm sorry but I forgot this entire issue until now...
I'm not that familiar with the event log viewer on windows so it might be that I missed something but there is nothing special in the application logs. There isn't anything special in the msi log either.
The only thing that happens (which hasn't been mentioned before in this issue) is the NETLOGON error from #276:

> Event ID:  3095
> Source:    NETLOGON
> This Windows NT computer is configured as a member of a workgroup, not as a member of a domain. The Netlogon service does not need to run in this configuration.

**Comment by enricogior** [comment] 2016-02-22 17:38
@lhecker 
did you try the [private build](http://1drv.ms/1OijQMj)?
If the application log doesn't show any Redis entry it means the code has not even been called since I've added an event log message as first instruction. The problem we saw in the past was a different issue since the actual Redis service was starting and then failing because of some configuration issues.

**Comment by lhecker** [comment] 2016-02-22 17:59
Yup @enricogior: I tried the private build and I've attached the relevant part of the Application Log in the Event Viewer: [Redis-x64-3.0.501-private.evtx.zip](https://github.com/MSOpenTech/redis/files/141112/Redis-x64-3.0.501-private.evtx.zip)

**Comment by enricogior** [comment] 2016-02-23 15:06
Thank you @lhecker 
the log doesn't show any Redis message, so it seems the problem is not in the Redis code but something goes wrong before the service is supposed to start.

**Comment by enricogior** [comment] 2016-02-29 17:10
Anyone else has tried to install using the private MSI?

**Comment by madcampos** [comment] 2016-03-06 21:45
Tryed with the private msi, it also fails in Windows 10, build 14271.
Didn't found a error on system log related to redis, oddly it says the instalation was successful

**Comment by enricogior** [comment] 2016-03-07 10:02
Hi @madcampos 
the different between the private build and the official build is in the logging, so if one fails the other one is supposed to fail as well.
I just tried again on Windows 10 build 14271 and it worked without error.
Could you please try to install the [2.8.2400 build](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2400) to verify if the problem is specific to the 3.0.x or not.
Thank you.

**Comment by madcampos** [comment] 2016-03-07 17:43
Sorry, my coment was ambiguous.
The 3.0.x private build gives the same error (`failed to start service`) and didn't finish the instalation. On the system log thre is no error related logs, only one saying it was successful.
I also tred the 2.8.2400 build, it gives the same problem and but i get the described error (`Verify that you have sufficient privileges to start system services.`) on log.
here i the output:

``` xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="MsiInstaller" /> 
  <EventID Qualifiers="0">11920</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-03-07T17:37:09.371637900Z" /> 
  <EventRecordID>1720</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Sleiphnir</Computer> 
  <Security UserID="S-1-5-21-971954099-1994782238-3004300373-1002" /> 
</System>
<EventData>
  <Data>Product: Redis on Windows -- Error 1920. Service 'Redis' (Redis) failed to start. Verify that you have sufficient privileges to start system services.</Data> 
  <Data>(NULL)</Data> 
  <Data>(NULL)</Data> 
  <Data>(NULL)</Data> 
  <Data>(NULL)</Data> 
  <Data>(NULL)</Data> 
  <Data /> 
  <Binary>7B36384437384630352D423434312D343041362D413337392D3944383039393935303132467D</Binary> 
</EventData>
</Event>
```

**Comment by enricogior** [comment] 2016-03-09 17:42
@madcampos 
thank you for trying the 2.8.2400 build.
We still haven't determine what causes the problem on some Windows 10 machines.
So far we haven't been able to reproduce the problem on our test machine, therefore any extra information may help: the type of account used, if the Windows 10 installation was an upgrade from a previous Windows version or a clean installation, if the machine has joined a domain and so on.
Thank you.

**Comment by madcampos** [comment] 2016-03-09 18:42
It was an upgrade from stable to preview (current build is 14271), I'm using an administrator account and the machine has not joined a domain.

**Comment by enricogior** [comment] 2016-03-09 19:30
@madcampos 
the Windows version is Home or Pro?

**Comment by enricogior** [comment] 2016-03-21 12:25
To everyone on this thread, can you please let me know if:
- the MSI failure occurs on an english version of Windows 10 or on a localized version?
- is the Windows 10 a clean install or an upgrade from a previous version of Windows?

Thank you.

**Comment by madcampos** [comment] 2016-03-21 12:28
sorry didn't answer (or it didn't send the email) on the previous question...
So, i'm using windows 10 pro, it's localized to pt-br and is an upgrade install.

**Comment by enricogior** [comment] 2016-03-21 13:18
@madcampos 
thank you.

**Comment by enricogior** [comment] 2016-03-22 17:22
Finally we were able to reproduce the problem on a Windows 10 localized machine and it turned out the problem is caused by the fact that the MSI is not setting the Network Service account correctly.
It seems only some languages are effected.
I'll notify when a fix will be ready.

**Comment by ioleo** [comment] 2016-03-22 19:40
Great to hear :)

**Comment by enricogior** [comment] 2016-03-23 17:48
So this turn out to be a bug in some localized version of Windows 10.
We have a workaround for it, but before releasing it we need more testing to make sure the workaround doesn't cause problems on other platforms.
In the worst case we will release a Windows 10 specific MSI along with the current one that works just fine on all other versions of Windows.

**Comment by lhecker** [comment] 2016-03-24 13:11
I think I should add that my machine is localized to de-De and the installation failed as I described above.

**Comment by enricogior** [comment] 2016-03-28 15:57
@loostro @manuelbieh @panyamin @lhecker @madcampos:
this is a modified version of the MSI that should work on the Windows 10 machines were the service failed to start.
Please let me know if it works for you.
Thank you.

[Redis-x64-3.0.501-Win10-Fix.zip](https://github.com/MSOpenTech/redis/files/192015/Redis-x64-3.0.501-Win10-Fix.zip)

**Comment by madcampos** [comment] 2016-03-28 19:09
@enricogior works like a charm.

**Comment by enricogior** [comment] 2016-03-29 13:12
@madcampos 
thank you very much for the feedback.

**Comment by ioleo** [comment] 2016-04-01 16:54
@enricogior 
Installed successfully, thanks

**Comment by coldrunMateusz** [comment] 2016-04-09 08:23
New installer helped with the same error on Windows 7 Home Premium

**Comment by enricogior** [comment] 2016-04-09 10:33
Hi @coldrunMateusz 
is a localized version of Windows 7?

**Comment by gearlles** [comment] 2016-04-11 14:35
The new installer also fixed for me. I'm using a localized version of Windows 7 Professional SP1. When will it be release?

**Comment by enricogior** [comment] 2016-04-11 14:38
Hi @gearlles 
thank you for the feedback.
The fix for the MSI will be in the next release, we are currently working on it and hopefully if we don't run into major issues it will be available before the end of the month.

**Comment by UweKeim** [comment] 2016-05-11 12:03
I had the error on a German Windows Server 2012 (non-R2), too.

Using the above Fix worked for me, too.

**Comment by enricogior** [comment] 2016-05-11 12:05
Hi @UweKeim 
thank you for the feedback.

**Comment by felixfbecker** [comment] 2016-06-17 09:43
@enricogior I have the same issue on Windows 10 Pro, German localization. The fix you uploaded worked. You originally stated April as the release date, now it's June, do you have an updated ETA?

**Comment by enricogior** [comment] 2016-06-17 09:49
@felixfbecker 
the fix was supposed to be part of the 3.0.7 release that has been delayed because of a serious bug that hasn't been fixed yet.
We might decide to release the MSI fix in 3.0.502.
Thank you.

**Comment by enricogior** [comment] 2016-06-21 09:15
This issue is now fixed in the [3.0.502 release](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.502).

**Closed as completed by enricogior** 2016-06-21 09:15 UTC
Labels: Solved

**Comment by enricogior** [comment] 2016-06-21 12:39
Update: the latest release is [3.0.503](https://github.com/MSOpenTech/redis/releases/tag/win-3.0.503).
Sorry about the double release in one day.
Thank you.

**Comment by gearlles** [comment] 2016-06-21 13:08
@enricogior Thanks, much appreciated.
