### ISSUE TITLE
Redis 2.8.2101 (00000000/0) 64 bit bug

### ISSUE THREAD

**Issue by doobang** [microsoftarchive/redis#398] opened 2016-01-29 01:35 UTC
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[5900] 29 Jan 09:31:10.112 # --- ABORT
[5900] 29 Jan 09:31:10.112 # --- STACK TRACE
redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:95)(0x00000016, 0x40149A50, 0x00000000, 0x00000001)
redis-server.exe!AbortHandler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:206)(0x00000016, 0x9F1C4A26, 0x00000003, 0x77A37DBA)
redis-server.exe!raise(f:\dd\vctools\crt\crtw32\misc\winsig.c:587)(0x00000001, 0x00000000, 0x000000B0, 0x0000009A)
redis-server.exe!abort(f:\dd\vctools\crt\crtw32\misc\abort.c:82)(0x00001000, 0x4012C210, 0x00000017, 0x400381C8)
redis-server.exe!dlmalloc(c:\release\redis\src\win32_interop\win32_dlmalloc.c:4638)(0x0000009A, 0xF54C1C48, 0xF54528C8, 0x00000000)
redis-server.exe!zmalloc(c:\release\redis\src\zmalloc.c:143)(0xF5452970, 0xF54C1C48, 0x00000001, 0x00000017)
redis-server.exe!rdbSaveLzfStringObject(c:\release\redis\src\rdb.c:229)(0xF5452970, 0x40083A93, 0x00000017, 0x00000017)
redis-server.exe!rdbSaveRawString(c:\release\redis\src\rdb.c:295)(0x41B93D4E, 0x00000001, 0xF5452990, 0xFFFFFFFF)
redis-server.exe!rdbSaveObject(c:\release\redis\src\rdb.c:513)(0x0012F8A0, 0x00000001, 0xF5452970, 0x00000001)
redis-server.exe!rdbSaveRio(c:\release\redis\src\rdb.c:692)(0x4012C210, 0x00000094, 0x00000000, 0x048D275C)
redis-server.exe!rdbSave(c:\release\redis\src\rdb.c:760)(0x00000094, 0x00000000, 0x00000094, 0x00000094)
redis-server.exe!QForkChildInit(c:\release\redis\src\win32_interop\win32_qfork.cpp:305)(0xFFFFFFFF, 0x00000000, 0x038D0000, 0x000000A4)
redis-server.exe!QForkStartup(c:\release\redis\src\win32_interop\win32_qfork.cpp:747)(0x002F97B0, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1348)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!__tmainCRTStartup(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
kernel32.dll!BaseThreadInitThunk(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[5900] 29 Jan 09:31:10.118 #
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

```
   Please report this bug by following the instructions at:

 http://github.com/MSOpenTech/redis/wiki/Submitting-an-Issue

Suspect RAM error? Use redis-server --test-memory to verify it.
```

**Comment by enricogior** [comment] 2016-01-29 03:38
Hi @doobang 
the crash is due to a memory allocation failure, likely caused by heap fragmentation. You may want to increase the maxheap or lower the maxmemory flag in order to increase the maxheap/maxmemory ratio.
Since v2.8.2101 we released new builds with several bug fixes, you should update.
Thank you.

**Comment by doobang** [comment] 2016-01-29 07:17
@enricogior ok i see 
thank you

**Comment by huhm** [comment] 2016-02-01 02:52
@enricogior  My Redis has also happened with this problem.
My data in Redis is about 556KB,and my config is like this:
``` 
maxheap 128000000 
timeout 60
bind 127.0.0.1
port 6379
##### The following is the default configuration###
tcp-backlog 511  
tcp-keepalive 0 
loglevel notice  
logfile "redis.log" 
syslog-ident redis 
databases 16 
save 900 1
save 300 10
save 60 10000 
stop-writes-on-bgsave-error yes 
rdbcompression yes 
rdbchecksum yes 
dbfilename dump_main.rdb 
dir ./ 
slave-serve-stale-data yes 
slave-read-only yes
 repl-diskless-sync no 
repl-diskless-sync-delay 5 
repl-disable-tcp-nodelay no 
slave-priority 100 
appendonly no 
appendfilename "appendonly.aof" 
appendfsync everysec 
no-appendfsync-on-rewrite no 
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb 
aof-load-truncated yes 
lua-time-limit 5000 
slowlog-log-slower-than 10000 
slowlog-max-len 128 
latency-monitor-threshold 0 
notify-keyspace-events "" 
hash-max-ziplist-entries 512
hash-max-ziplist-value 64 
list-max-ziplist-entries 512
list-max-ziplist-value 64 
set-max-intset-entries 512
 
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
 
hll-sparse-max-bytes 3000
 
activerehashing yes
 
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit slave 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60 
hz 10 
aof-rewrite-incremental-fsync yes
 
```
The Redis works well in my another server which the maxheap
is 256000000 
If I change the maxheap ,could the problem be solved?

**Comment by enricogior** [comment] 2016-02-19 06:54
I'm closing this issue as a duplicate of https://github.com/MSOpenTech/redis/issues/310

**Closed as completed by enricogior** 2016-02-19 06:54 UTC
Labels: Architecture limitation
