### ISSUE TITLE
Redis bgsave fails and prevents any further persistence

### ISSUE THREAD

**Issue by JeHoDe** [microsoftarchive/redis#289] opened 2015-08-05 18:23 UTC
I'm runnin redis as a windows service (with the default settings). From time to time the bgsave command fails. I only can resolve this issue by re-starting the service (and loosing all data since the last successful bgsave :-( ) This is what the redis info command says (the info command has been run after the service restart):
# Server

redis_version:2.8.19
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:9968db13395be4aa
redis_mode:standalone
os:Windows
arch_bits:64
multiplexing_api:winsock_IOCP
gcc_version:0.0.0
process_id:1208
run_id:de4f7916b1a32b53648cd774ebe3a5f95e64d5a0
tcp_port:6379
uptime_in_seconds:9626
uptime_in_days:0
hz:10
lru_clock:12735354
config_file:C:\Program Files\Redis\redis_store.conf
# Clients

connected_clients:1
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
# Memory

used_memory:131435032
used_memory_human:125.35M
used_memory_rss:131383704
used_memory_peak:132169328
used_memory_peak_human:126.05M
used_memory_lua:35840
mem_fragmentation_ratio:1.00
mem_allocator:dlmalloc-2.8
# Persistence

loading:0
rdb_changes_since_last_save:16
rdb_bgsave_in_progress:0
rdb_last_save_time:1438798500
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:1438798501
rdb_current_bgsave_time_sec:-1
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
# Stats

total_connections_received:1146
total_commands_processed:19651
instantaneous_ops_per_sec:1
total_net_input_bytes:963058
total_net_output_bytes:0
instantaneous_input_kbps:0.04
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:1
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:44
keyspace_misses:1217
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:93601
# Replication

role:master
connected_slaves:1
slave0:ip=62.50.117.49,port=6379,state=online,offset=233779,lag=1
master_repl_offset:233779
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:2
repl_backlog_histlen:233778
# CPU

used_cpu_sys:11.28
used_cpu_user:2.11
used_cpu_sys_children:0.00
used_cpu_user_children:0.00
# Keyspace

db0:keys=375844,expires=0,avg_ttl=0
# Logfile

Here is the relevant part of the logfile:

[1716] 05 Aug 06:49:32.088 \* Background saving terminated with success
[1716] 05 Aug 06:54:33.045 \* 10 changes in 300 seconds. Saving...
[1716] 05 Aug 06:54:34.652 # fork operation complete
[1716] 05 Aug 06:54:34.839 \* Background saving terminated with success
[1716] 05 Aug 06:59:35.001 \* 10 changes in 300 seconds. Saving...
[1716] 05 Aug 06:59:36.841 # fork operation complete
[1716] 05 Aug 06:59:37.075 \* Background saving terminated with success
[1716] 05 Aug 07:04:38.033 \* 10 changes in 300 seconds. Saving...
[1716] 05 Aug 07:04:38.033 # BeginForkOperation: system error caught. error code=0x000005af, message=BeginForkOperation: VirtualProtect failed: unknown error

[1716] 05 Aug 07:04:38.033 # Can't save in background: fork: Invalid argument
[1716] 05 Aug 07:04:38.142 \* 10 changes in 300 seconds. Saving...
[1716] 05 Aug 07:04:39.905 # fork operation complete
[1716] 05 Aug 07:04:40.092 \* Background saving terminated with success
[1716] 05 Aug 07:09:41.002 \* 10 changes in 300 seconds. Saving...
[1716] 05 Aug 07:09:41.002 # BeginForkOperation: system error caught. error code=0x000005af, message=BeginForkOperation: VirtualProtect failed: unknown error

[1716] 05 Aug 07:09:41.002 # Can't save in background: fork: Invalid argument
[1716] 05 Aug 07:09:41.111 \* 10 changes in 300 seconds. Saving...
[1716] 05 Aug 07:09:41.111 # BeginForkOperation: system error caught. error code=0x000005af, message=BeginForkOperation: VirtualProtect failed: unknown error

[1716] 05 Aug 07:09:41.111 # Can't save in background: fork: Invalid argument
[1716] 05 Aug 07:09:41.221 \* 10 changes in 300 seconds. Saving...
[1716] 05 Aug 07:09:43.030 # fork operation complete
[1716] 05 Aug 07:09:43.217 \* Background saving terminated with success
[1716] 05 Aug 07:14:44.034 \* 10 changes in 300 seconds. Saving...
[1716] 05 Aug 07:14:44.034 # BeginForkOperation: system error caught. error code=0x000005af, message=BeginForkOperation: VirtualProtect failed: unknown error

[1716] 05 Aug 07:14:44.034 # Can't save in background: fork: Invalid argument
[1716] 05 Aug 07:14:44.143 \* 10 changes in 300 seconds. Saving...
[1716] 05 Aug 07:14:44.143 # BeginForkOperation: system error caught. error code=0x000005af, message=BeginForkOperation: VirtualProtect failed: unknown error

**Comment by enricogior** [comment] 2015-08-05 18:37
Hi @JeHoDe,
thank you for reporting the issue.
The problem seems caused by the fact that the system paging file is not large enough or is too fragmented to map the virtual memory of the child process.
Please take the time to read the [Memory Configuration](https://github.com/MSOpenTech/redis/wiki/Memory-Configuration) wiki page.
Also, consider updating to the latest [v2.8.2101 release](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2101).
If the problem still persists, please let us know.

**Comment by enricogior** [comment] 2015-09-03 09:13
Closing this issue since it hasn't been updated in a month.
The problem was originally caused by "The paging file is too small for this operation to complete."
Increasing the system paging file size should prevent the error to occur.
If the error occurs in latest builds, a more informative error message is displayed.

**Closed as completed by enricogior** 2015-09-03 09:13 UTC
