### ISSUE TITLE
accept: Unknown error

### ISSUE THREAD

**Issue by linyuliang** [microsoftarchive/redis#160] opened 2014-08-13 07:24 UTC
It seems like a random error. The redis server is running. But when the jedis client get a connection, it gets an connect refused error.
redis 2.8.12 32bit or redis 2.8.9 64bit runs under windows 2008 server 32bit or 64bit

![redis](https://cloud.githubusercontent.com/assets/3059826/3902193/8bf0e634-22ba-11e4-8108-29b2abd3a8a5.jpg)

**Comment by jepickett** [comment] 2014-08-13 21:26
I am not seeing the problem you are. I did the following:
1. Installed JDK 8u11 x64
2. Installed Eclipse
3. Built a hello world program via the eclipse tutorial to verify install of eclipse and java
4. Downloaded jedis-2.4.2 jar and commons-pool-2.0 jar
5. Added the jars to referenced libraries on my hello world project
6. Modified the hello world code as follows:

``` Java
import redis.clients.jedis.*;
public class HelloWorld {
    static private JedisPool pool;
    public static void main(String[] args) { 
        try {
            pool = new JedisPool(new JedisPoolConfig(),"localhost");
            Jedis jedis = pool.getResource();
            jedis.set("hello", "world");
            String result = jedis.get("hello");
            System.out.println("[hello]=" + result);
            pool.returnResource(jedis);
            pool.destroy();
        }
        catch (Exception e) {
            System.err.println(e.toString());
        }
    }
}
```

I verified with redis-cli that redis contained the data expected. I also tried this with the x64 and x86 binaries. What is different with your setup? If you try this on another machine do you get the same result?

**Comment by linyuliang** [comment] 2014-08-14 07:08
After a period of running, the error occured, looks like a random. I can not reproduce the problem also.I used the default config file redis.windows.config.
And the jar libs I used are:
    //Redis Begin
    compile group: "org.springframework.data",name:"spring-data-redis", version: "1.3.1.RELEASE"
    compile group: "redis.clients",name:"jedis", version: "2.5.1"
    //Redis end

**Comment by jepickett** [comment] 2014-08-15 02:43
Since we can't reproduce this , there is not much I can do. I will leave this open for a week to see if anyone else can reproduce the problem.

**Comment by jepickett** [comment] 2014-08-22 02:50
Closing due to lack of reproduction scenario.

**Closed as completed** 2014-08-25 22:12 UTC
