### ISSUE TITLE
-dup-sentinel flood in log

### ISSUE THREAD

**Issue by Fr1z2r** [microsoftarchive/redis#311] opened 2015-09-08 13:23 UTC
Hi.

I try to configure the HA for redis-server on a 3 node setup.
1 master + 2 slaves + 3 sentinels.

sentinel.conf(same on all nodes):
logfile "Logs/sentinel_log.txt"
sentinel monitor mymaster redis 6379 2

In sentinel logs I have a lot of messages like this:
[6640] 04 Sep 16:52:54.465 \* +sentinel sentinel [fe80::_]:26379 fe80::_ 26379 @ mymaster 192.168._.34 6379
[6640] 04 Sep 16:52:56.293 \* -dup-sentinel master mymaster 192.168._.34 6379 #duplicate of 192.168._.34:26379 or 09202a1d681bf5fa86cb751586239e00a
0fa8c1
[6640] 04 Sep 16:52:56.293 \* +sentinel sentinel 192.168._.34:26379 192.168._.34 26379 @ mymaster 192.168._.34 6379
[6640] 04 Sep 16:52:56.606 \* -dup-sentinel master mymaster 192.168._.34 6379 #duplicate of fe80::_26379 or 09202a1d681bf5fa86cb7
1586239e00a20fa8c1

Why is this happening?

**Comment by enricogior** [comment] 2015-09-08 15:20
Hi @Fr1z2r 
the issue seems not Windows-specific: https://github.com/antirez/redis/issues/2309

**Comment by Fr1z2r** [comment] 2015-09-08 16:44
But this scheme with same configs works fine on linux nodes (without flooding).

Redis version on linux(centos): 2.8.19
Redis version on win: 2.8.2102

**Comment by enricogior** [comment] 2015-09-08 17:22
@Fr1z2r 
in https://github.com/antirez/redis/issues/2309 they don't mention Windows, the problem doesn't seem to be platform specific but caused by the host configuration.
Have you already tried to follow the suggestion made by miccrun in https://github.com/antirez/redis/issues/2309?
I would also try replacing `redis` with the IP address in `sentinel monitor mymaster redis 6379 2`

**Comment by Fr1z2r** [comment] 2015-09-08 18:42
I try to use IP instead of hostname - it doesn't help.
How can I apply miccrun suggestion to a Windows host? In system32/drivers/ets/hosts all lines commented.

**Comment by Fr1z2r** [comment] 2015-09-08 19:18
I add "bind 0.0.0.0" to redis.conf and flood stopped

**Comment by enricogior** [comment] 2015-10-15 17:14
@Fr1z2r 
release [v2.8.2104](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2104) has a fix for this issue, please see the release note for details.

**Closed as completed by enricogior** 2015-10-15 17:14 UTC
