### ISSUE TITLE
Assertion Failed: 'zslDelete(zs->zsl,curscore,curobj)' is not true

### ISSUE THREAD

**Issue by Psigio** [microsoftarchive/redis#190] opened 2014-10-30 16:51 UTC
Hi,

We have another assertion failure in Redis 2.8.14 on Server 2008 R2 on a VM (see below) - I'm guessing it's probably due to something wrong with our machine (see #184, #185) unless you've seen this issue somewhere else?  We recently re-activated slaving on this particular instance which is acting as a master:

```
[1996] 30 Oct 16:15:50.201 * Slave asks for synchronization
[1996] 30 Oct 16:15:50.242 * Full resync requested by slave.
[1996] 30 Oct 16:15:50.242 * Waiting for next BGSAVE for SYNC
[1996] 30 Oct 16:16:28.307 # fork operation complete
[1996] 30 Oct 16:16:34.764 * Background saving terminated with success
[1996] 30 Oct 16:16:38.509 # 
=== REDIS BUG REPORT START: Cut & paste starting from here ===
[1996] 30 Oct 16:16:38.509 # === ASSERTION FAILED CLIENT CONTEXT ===
[1996] 30 Oct 16:16:38.509 # client->flags = 0
[1996] 30 Oct 16:16:38.509 # client->fd = 25
[1996] 30 Oct 16:16:38.509 # client->argc = 4
[1996] 30 Oct 16:16:38.509 # client->argv[0] = "ZADD" (refcount: 1)
[1996] 30 Oct 16:16:38.509 # client->argv[1] = "LastUpdate" (refcount:     1)
[1996] 30 Oct 16:16:38.509 # client->argv[2] = "131049896326469" (refcount: 1)
[1996] 30 Oct 16:16:38.509 # client->argv[3] = "48295012" (refcount: 1)
[1996] 30 Oct 16:16:38.509 # === ASSERTION FAILED OBJECT CONTEXT ===
[1996] 30 Oct 16:16:38.509 # Object type: 0
[1996] 30 Oct 16:16:38.509 # Object encoding: 0
[1996] 30 Oct 16:16:38.510 # Object refcount: 2
[1996] 30 Oct 16:16:38.510 # Object raw string len: zu
[1996] 30 Oct 16:16:38.510 # Object raw string content: "48295012"
[1996] 30 Oct 16:16:38.510 # === ASSERTION FAILED ===
[1996] 30 Oct 16:16:38.510 # ==> ..\src\t_zset.c:1280 'zslDelete(zs->zsl,curscore,curobj)' is not true
```

**Comment by jepickett** [comment] 2014-11-14 19:34
Closing this as a likely duplicate of 185.

**Closed as completed by jepickett** 2014-11-14 19:34 UTC
