### ISSUE TITLE
Redis Server stops accepting connections.

### ISSUE THREAD

**Issue by ravynz** [microsoftarchive/redis#281] opened 2015-07-31 14:41 UTC
We have been using a variety of the releases of redis, we are currently on 2.8.2101, but the same issue existed in 8.21 and I believe also in 8.17.  We run it on an older machine running windows 2008 r2.  The service runs fine, but will suddenly and for no apparent reason stop accepting connections.  It hasn't crashed, and the only indication of it is network traffic drops and we can't connect with the redis-cli client.  

In the logs you can see the client failing to connect with the following :

[2844] 30 Jul 07:48:30.072 # Accepting client connection: accept: Unknown error

Restarting the service will usually fix this, although sometimes it takes stopping the service and waiting 5-10 seconds then restarting.

**Comment by enricogior** [comment] 2015-07-31 14:46
Hi @ravynz 
thank you for reporting the issue, can you please provide some more information:
- the redis-server log 
- the redis-server config file
  They may help to determine the cause of the problem.
  Feel free to send the files to <_email edited_>.
  Thank you.

**Comment by ravynz** [comment] 2015-07-31 15:24
The files have been sent.  The current configuration is a single master on one machine.  We do have sentinels running on other machines because we were using a master slave setup on two machines, but that was causing crashes.  I will be adding those crash logs in another thread.  The config files were the same for that though.

**Comment by enricogior** [comment] 2015-07-31 15:25
@ravynz  thank you.

**Comment by enricogior** [comment] 2015-08-03 11:09
@ravynz 
this is now fixed, I'll try to fix #282 as well before releasing a new build.
Thank you.

**Comment by enricogior** [comment] 2015-08-25 14:30
@ravynz,
this bug has also been fixed in [v2.8.2102](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2102).
Thank you.

**Closed as completed by enricogior** 2015-08-25 14:30 UTC
Labels: Bug, P1
