### ISSUE TITLE
Redis Service dies after a few days 

### ISSUE THREAD

**Issue by goleafs** [microsoftarchive/redis#288] opened 2015-08-04 21:01 UTC
Using the Redis Windows Service with all default config.
Redis 2.8.21 (00000000/0) 64 bit, stand alone mode, port 6379

It runs well for a while, then after what seems like a few days it randomly seems to die... here are the Event log entries...

syslog-ident = redis

=== REDIS BUG REPORT START: Cut & paste starting from here ===
syslog-ident = redis
--- EXCEPTION_ACCESS_VIOLATION
syslog-ident = redis
--- INFO OUTPUT
Faulting application name: redis-server.exe, version: 0.0.0.0, time stamp: 0x558b1f29
Faulting module name: redis-server.exe, version: 0.0.0.0, time stamp: 0x558b1f29
Exception code: 0xc0000005
Fault offset: 0x0000000000086a34
Faulting process id: 0x734
Faulting application start time: 0x01d0cafdb94cd7a1
Faulting application path: C:\Program Files\Redis\redis-server.exe
Faulting module path: C:\Program Files\Redis\redis-server.exe
Report Id: fef3c19e-3add-11e5-80c5-00155d018000
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: redis-server.exe
P2: 0.0.0.0
P3: 558b1f29
P4: redis-server.exe
P5: 0.0.0.0
P6: 558b1f29
P7: c0000005
P8: 0000000000086a34
P9: 
P10: 

Attached files:
C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\WERB1BA.tmp.appcompat.txt
C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp\WERB1CB.tmp.WERInternalMetadata.xml
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_redis-server.exe_e6fcaa5ef6f9ebff0fc8eac53205878b8f29c11_e1be9887_cab_7244b1d9\memory.hdmp
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_redis-server.exe_e6fcaa5ef6f9ebff0fc8eac53205878b8f29c11_e1be9887_cab_7244b1d9\triagedump.dmp
WERGenerationLog.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_redis-server.exe_e6fcaa5ef6f9ebff0fc8eac53205878b8f29c11_e1be9887_cab_7244b1d9

Analysis symbol: 
Rechecking for solution: 0
Report Id: fef3c19e-3add-11e5-80c5-00155d018000
Report Status: 4
Hashed bucket:

**Comment by enricogior** [comment] 2015-08-04 21:48
Hi @goleafs 
thank you for reporting the issue.
Do you still have the log that shows the crash? If possible post the previous 50 lines.
I'm asking it because the bug report doesn't include a stack trace so I need to verify if the bug is the one we fixed in [v2.8.2101](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2101)
Most of the crashes reported for v2.8.21 were caused by it and it can be verified checking the log just before the crash.
Thank you.

**Comment by goleafs** [comment] 2015-08-04 21:50
I think so.. is it in one of the files mentioned above?

**Comment by enricogior** [comment] 2015-08-04 21:57
@goleafs
when Redis is running as a windows service, the log file is located by default here:

C:\Program Files\Redis\Logs\redis_log.txt

the log file uses the unix new line convention, so it's better to open it with a program like Notepad++ to see the correct formatting.

**Comment by goleafs** [comment] 2015-08-04 22:09
Here are the last couple entries around the crashes..

[1844] 04 Aug 15:21:14.185 \* 10 changes in 300 seconds. Saving...
[1844] 04 Aug 15:21:14.623 # fork operation complete
[1844] 04 Aug 15:21:14.951 \* Background saving terminated with success
[1844] 04 Aug 15:21:22.548 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[1844] 04 Aug 15:21:22.548 # --- EXCEPTION_ACCESS_VIOLATION
[1844] 04 Aug 15:21:22.548 # --- INFO OUTPUT
[7956] 04 Aug 16:40:59.702 \* Redis 2.8.21 (00000000/0) 64 bit, stand alone mode, port 6379, pid 7956 ready to start.
[7956] 04 Aug 16:40:59.702 # Server started, Redis version 2.8.21
[7956] 04 Aug 16:40:59.702 \* DB loaded from disk: 0.001 seconds
[7956] 04 Aug 16:40:59.702 \* The server is now ready to accept connections on port 6379
[7956] 04 Aug 16:56:00.071 \* 1 changes in 900 seconds. Saving...
[7956] 04 Aug 16:56:00.540 # fork operation complete
[7956] 04 Aug 16:56:00.868 \* Background saving terminated with success

[1244] 30 Jul 14:10:25.560 \* 10 changes in 300 seconds. Saving...
[1244] 30 Jul 14:10:25.998 # fork operation complete
[1244] 30 Jul 14:10:26.310 \* Background saving terminated with success
[1244] 30 Jul 14:13:11.439 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[1244] 30 Jul 14:13:11.439 # --- EXCEPTION_ACCESS_VIOLATION
[1244] 30 Jul 14:13:11.439 # --- INFO OUTPUT
[1844] 30 Jul 15:27:08.044 \* Redis 2.8.21 (00000000/0) 64 bit, stand alone mode, port 6379, pid 1844 ready to start.
[1844] 30 Jul 15:27:08.044 # Server started, Redis version 2.8.21
[1844] 30 Jul 15:27:08.044 \* DB loaded from disk: 0.000 seconds
[1844] 30 Jul 15:27:08.044 \* The server is now ready to accept connections on port 6379
[1844] 30 Jul 15:32:39.636 \* 10 changes in 300 seconds. Saving...
[1844] 30 Jul 15:32:40.074 # fork operation complete
[1844] 30 Jul 15:32:40.386 \* Background saving terminated with success
[1844] 30 Jul 15:37:41.025 \* 10 changes in 300 seconds. Saving...
[1844] 30 Jul 15:37:41.462 # fork operation complete
[1844] 30 Jul 15:37:41.774 \* Background saving terminated with success

**Comment by enricogior** [comment] 2015-08-04 22:23
@goleafs 
the log doesn't contain the definitive proof that I was looking for but some of the info matches the characteristics of the bug we fixed in [v2.8.2101](https://github.com/MSOpenTech/redis/releases/tag/win-2.8.2101), so please update to the latest release.
Thank you.

**Comment by goleafs** [comment] 2015-08-04 22:29
Ok, I'll try it.. btw in the meantime I got another error as well..

[7956] 04 Aug 18:03:15.297 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[7956] 04 Aug 18:03:15.297 # --- ABORT
[7956] 04 Aug 18:03:15.297 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

```
   Please report this bug by following the instructions at:

 http://github.com/MSOpenTech/redis/wiki/Submitting-an-Issue

Suspect RAM error? Use redis-server --test-memory to verify it.
```

[2956] 04 Aug 18:26:55.045 \* Redis 2.8.21 (00000000/0) 64 bit, stand alone mode, port 6379, pid 2956 ready to start.
[2956] 04 Aug 18:26:55.045 # Server started, Redis version 2.8.21
[2956] 04 Aug 18:26:55.045 \* DB loaded from disk: 0.001 seconds
[2956] 04 Aug 18:26:55.045 \* The server is now ready to accept connections on port 6379

**Comment by enricogior** [comment] 2015-08-04 22:35
@goleafs 
the 2.8.2101 also contains a fix for the BUG REPORT that wasn't printing the STACK TRACE section, without the stack trace it's really difficult to determine the exact cause of the crash.
The last report seems to be an out of memory error but without the stack trace it can't be said for sure.

**Comment by enricogior** [comment] 2015-11-27 10:11
@goleafs 
closing the issue since it refer to an old release.
Feel free to re-open it if needed.
Thank you.

**Closed as completed by enricogior** 2015-11-27 10:11 UTC
Labels: Old release
