### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by bladefist** [microsoftarchive/redis#271] opened 2015-07-18 14:37 UTC
Using the latest version got this error after several days of use:

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[11852] 17 Jul 13:44:28.326 # --- EXCEPTION_ACCESS_VIOLATION
[11852] 17 Jul 13:44:28.326 # --- STACK TRACE
redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktra
ce.cpp:95)(0x0013E7C0, 0x0013FF90, 0x00000001, 0x40105AA8)
redis-server.exe!UnhandledExceptiontHandler(c:\release\redis\src\win32_interop\w
in32_stacktrace.cpp:185)(0x00000000, 0x00000000, 0x00000000, 0x00000008)
KERNELBASE.dll!UnhandledExceptionFilter(c:\release\redis\src\win32_interop\win32
_stacktrace.cpp:185)(0x00000000, 0x51A1AD74, 0x00000000, 0x00000000)
ntdll.dll!memset(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0x
40016A27, 0x00000000, 0x0013EF00, 0x4005503F)
ntdll.dll!_C_specific_handler(c:\release\redis\src\win32_interop\win32_stacktrac
e.cpp:185)(0x00000000, 0x0013E930, 0x0013F3F0, 0x0013F3F0)
ntdll.dll!_chkstk(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:185)(0
x00000001, 0x51910000, 0x00000000, 0x51A41178)
ntdll.dll!RtlRaiseException(c:\release\redis\src\win32_interop\win32_stacktrace.
cpp:185)(0x002B002B, 0x00000000, 0x14A12A00, 0x00000000)
ntdll.dll!KiUserExceptionDispatcher(c:\release\redis\src\win32_interop\win32_sta
cktrace.cpp:185)(0x14A12A10, 0x40092E7E, 0x00000552, 0x00000552)
redis-server.exe!dlfree(c:\release\redis\src\win32_interop\win32_dlmalloc.c:4822
)(0x00000004, 0x000016D8, 0x0013F6F1, 0x0013F8A0)
redis-server.exe!zfree(c:\release\redis\src\zmalloc.c:222)(0x00000005, 0x0013F6F
1, 0x00000000, 0x0013F6F1)
redis-server.exe!rdbSaveLzfStringObject(c:\release\redis\src\rdb.c:249)(0x000000
42, 0x0C6F81A8, 0x000000C3, 0x0995E298)
redis-server.exe!rdbSaveRawString(c:\release\redis\src\rdb.c:295)(0x0013F8A0, 0x
0000003C, 0x4003EF00, 0x0D67A890)
redis-server.exe!rdbSaveObject(c:\release\redis\src\rdb.c:605)(0x0013F8A0, 0x000
00001, 0x17203C50, 0x17203C50)
redis-server.exe!rdbSaveRio(c:\release\redis\src\rdb.c:692)(0x4012C210, 0x000000
F8, 0x00000000, 0x047B275C)
redis-server.exe!rdbSave(c:\release\redis\src\rdb.c:760)(0x000000F8, 0x00000000,
 0x000000F8, 0x000000F8)
redis-server.exe!QForkChildInit(c:\release\redis\src\win32_interop\win32_qfork.c
pp:305)(0xFFFFFFFF, 0x00000000, 0x037B0000, 0x00000108)
redis-server.exe!QForkStartup(c:\release\redis\src\win32_interop\win32_qfork.cpp
:747)(0x00207F90, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1348)(0
x00000000, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!__tmainCRTStartup(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(
0x00000000, 0x00000000, 0x00000000, 0x00000000)
KERNEL32.DLL!BaseThreadInitThunk(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x
00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x0000
0000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x0000
0000, 0x00000000, 0x00000000, 0x00000000)
[11852] 17 Jul 13:44:28.353 # --- INFO OUTPUT
[13360] 18 Jul 09:35:23.011 # User requested shutdown...
[13360] 18 Jul 09:35:23.011 # There is a child saving an .rdb. Killing it!
[13360] 18 Jul 09:35:23.011 # AbortForkOperation(): 0x00000005 - EndForkOperatio
n: Killing forked process failed.: permission denied

**Comment by enricogior** [comment] 2015-07-18 15:00
Hi @bladefist 
thank you for the report, we'll look into it.

**Comment by enricogior** [comment] 2015-07-18 16:19
@bladefist,
the crash happened in the child process while saving the RDB file.
Did the server stop responding after that? 
If not, it would be useful to see the rest of the log after the crash to know if there are any successful saves afterward, you can search for "Background saving terminated with success" or as an alternative feel free to send me a copy of the log to ---edited---.
Thank you.

**Comment by bladefist** [comment] 2015-07-18 16:23
@enricogior  emailed you

**Comment by bladefist** [comment] 2015-07-22 20:13
@enricogior Is this something that I can fix by doing something different or changing up my configuration? Or is this a bug in the app.  Excited to get my redis cache back up.

Thanks!

**Comment by enricogior** [comment] 2015-07-23 13:37
@bladefist,
did the same crash happen again?
I haven't found a way to reproduce the crash so the investigation is not easy.
What I can tell from the crash report is what happened but not what has caused it.
The crash occurred in the child process while saving the rdb file to the disk.
It's Redis code wrapped in Windows specific code, I don't think it's a bug in the Redis code, it's rather a problem of the Windows wrapper that interferes with the Redis code: a valid pointer suddenly became invalid causing the access violation (memory corruption).
Without a way to reproduce it, it's really difficult to figure out what exactly is causing it.

**Comment by enricogior** [comment] 2015-11-16 16:40
@bladefist 
since July we have released several updates to fix various crashes.
I'm closing the issue since there hasn't been any activity on it for a while.
Please feel free to reopen it if the problem still persists using the latest release.
Thank you.

**Closed as completed by enricogior** 2015-11-16 16:40 UTC
Labels: Bug, P1

**Comment by bladefist** [comment] 2015-11-16 16:45
@enricogior  thanks! I've been using a version that was released around sept or oct and it has been stable so far. Thank you.
