### ISSUE TITLE
"decrRefCount against refCount <=0" error

### ISSUE THREAD

**Issue by Psigio** [microsoftarchive/redis#176] opened 2014-10-09 15:00 UTC
Hi,

Our Redis 2.8.14 installation on Windows Server 2008 R2 crashed with the following error apparently just after a (quite long running) background save:

```
[11320] 08 Oct 21:53:01.008 * 10000 changes in 60 seconds. Saving...
[11320] 08 Oct 21:59:21.292 # fork operation complete
[11320] 08 Oct 21:59:28.988 * Background saving terminated with success
[11320] 08 Oct 21:59:29.228 # 

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[11320] 08 Oct 21:59:29.228 # ------------------------------------------------
[11320] 08 Oct 21:59:29.228 # !!! Software Failure. Press left mouse button to continue
[11320] 08 Oct 21:59:29.228 # Guru Meditation: "decrRefCount against refcount <= 0" #..\src\object.c:233
[11320] 08 Oct 21:59:29.228 # ------------------------------------------------
```

Do you know what might be the root cause?

Thanks

**Comment by jepickett** [comment] 2014-10-20 21:53
What is your system configuration (physical/virtual,ram,page file settings)?

**Comment by Psigio** [comment] 2014-10-21 09:26
Hi, the machine has 16Gb Physical RAM, 32Gb Page File (fixed size) and about 10Gb spare hard disk space (after the Redis 6gb heap file has been written out during startup).

**Comment by jepickett** [comment] 2014-11-14 19:35
Closing this as a likely duplicate of 185.

**Closed as completed by jepickett** 2014-11-14 19:35 UTC
