### ISSUE TITLE
Redis server crashed with abort

### ISSUE THREAD

**Issue by chester89** [microsoftarchive/redis#316] opened 2015-09-15 17:04 UTC
I recently received this error from 2.8.2101 release:

=== REDIS BUG REPORT START: Cut & paste starting from here ===
[4856] 15 Sep 12:20:06.294 # --- ABORT
[4856] 15 Sep 12:20:06.294 # --- STACK TRACE
redis-server.exe!LogStackTrace(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:95)(0x00000016, 0x40149A50, 0x00000000, 0x00000001)
redis-server.exe!AbortHandler(c:\release\redis\src\win32_interop\win32_stacktrace.cpp:206)(0x00000016, 0xB47F3514, 0x40000000, 0x77869CAA)
redis-server.exe!raise(f:\dd\vctools\crt\crtw32\misc\winsig.c:587)(0x00000001, 0x00000000, 0x000000B0, 0x0000009B)
redis-server.exe!abort(f:\dd\vctools\crt\crtw32\misc\abort.c:82)(0x00001000, 0x400381C8, 0x00000000, 0x400381C8)
redis-server.exe!dlmalloc(c:\release\redis\src\win32_interop\win32_dlmalloc.c:4656)(0x0000009B, 0x00000018, 0xF9D95FB8, 0x400381C8)
redis-server.exe!zmalloc(c:\release\redis\src\zmalloc.c:143)(0x00000001, 0x4003123A, 0x4003EF00, 0x0012F780)
redis-server.exe!rdbSaveLzfStringObject(c:\release\redis\src\rdb.c:229)(0x00000001, 0x00000001, 0x0012F780, 0x40092E7E)
redis-server.exe!rdbSaveRawString(c:\release\redis\src\rdb.c:295)(0x0012F8A0, 0x00000001, 0xF9EBF103, 0xF9EB83D0)
redis-server.exe!rdbSaveObject(c:\release\redis\src\rdb.c:575)(0x0012F8A0, 0x00000001, 0xF9D96380, 0x00000001)
redis-server.exe!rdbSaveRio(c:\release\redis\src\rdb.c:692)(0x4012C210, 0x0000008C, 0x00000000, 0x0453275C)
redis-server.exe!rdbSave(c:\release\redis\src\rdb.c:760)(0x0000008C, 0x00000000, 0x0000008C, 0x0000008C)
redis-server.exe!QForkChildInit(c:\release\redis\src\win32_interop\win32_qfork.cpp:305)(0xFFFFFFFF, 0x00000000, 0x03530000, 0x000000A0)
redis-server.exe!QForkStartup(c:\release\redis\src\win32_interop\win32_qfork.cpp:747)(0x001B0240, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!main(c:\release\redis\src\win32_interop\win32_qfork.cpp:1348)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
redis-server.exe!__tmainCRTStartup(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
kernel32.dll!BaseThreadInitThunk(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
ntdll.dll!RtlUserThreadStart(f:\dd\vctools\crt\crtw32\startup\crt0.c:255)(0x00000000, 0x00000000, 0x00000000, 0x00000000)
[4856] 15 Sep 12:20:07.029 # 
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

I use Windows Server 2008 R2, both aof and rdb are turned on and I run redis-server from a console with a specific config file.

**Comment by enricogior** [comment] 2015-09-15 17:27
Hi @chester89,
it's a memory corruption that seems similar to a problem we have seen in the past, can you please post the log before the crash? 50 lines should be enough.
Thank you.

**Comment by chester89** [comment] 2015-09-15 18:53
​Of course. I don't have the most verbose logging set up, I'm afraid.

[2344] 15 Sep 10:45:06.154 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 10:45:06.154 \* Background saving started by pid 3216
[2344] 15 Sep 10:45:07.279 # fork operation complete
[2344] 15 Sep 10:45:07.279 \* Background saving terminated with success
[2344] 15 Sep 10:50:00.435 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 10:50:00.435 \* Background saving started by pid 4808
[2344] 15 Sep 10:50:00.857 # fork operation complete
[2344] 15 Sep 10:50:00.857 \* Background saving terminated with success
[2344] 15 Sep 11:00:05.654 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 11:00:05.654 \* Background saving started by pid 4500
[2344] 15 Sep 11:00:06.294 # fork operation complete
[2344] 15 Sep 11:00:06.294 \* Background saving terminated with success
[2344] 15 Sep 11:05:00.529 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 11:05:00.529 \* Background saving started by pid 3248
[2344] 15 Sep 11:05:01.232 # fork operation complete
[2344] 15 Sep 11:05:01.232 \* Background saving terminated with success
[2344] 15 Sep 11:15:05.107 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 11:15:05.107 \* Background saving started by pid 3844
[2344] 15 Sep 11:15:05.529 # fork operation complete
[2344] 15 Sep 11:15:05.529 \* Background saving terminated with success
[2344] 15 Sep 11:20:01.513 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 11:20:01.513 \* Background saving started by pid 2432
[2344] 15 Sep 11:20:02.263 # fork operation complete
[2344] 15 Sep 11:20:02.263 \* Background saving terminated with success
[2344] 15 Sep 11:30:03.951 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 11:30:03.951 \* Background saving started by pid 3176
[2344] 15 Sep 11:30:05.248 # fork operation complete
[2344] 15 Sep 11:30:05.248 \* Background saving terminated with success
[2344] 15 Sep 11:35:00.654 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 11:35:00.654 \* Background saving started by pid 3564
[2344] 15 Sep 11:35:01.404 # fork operation complete
[2344] 15 Sep 11:35:01.404 \* Background saving terminated with success
[2344] 15 Sep 11:40:07.263 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 11:40:07.263 \* Background saving started by pid 3724
[2344] 15 Sep 11:40:07.810 # fork operation complete
[2344] 15 Sep 11:40:07.810 \* Background saving terminated with success
[2344] 15 Sep 11:45:05.138 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 11:45:05.138 \* Background saving started by pid 2820
[2344] 15 Sep 11:45:05.685 # fork operation complete
[2344] 15 Sep 11:45:05.685 \* Background saving terminated with success
[2344] 15 Sep 11:50:00.466 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 11:50:00.466 \* Background saving started by pid 3192
[2344] 15 Sep 11:50:01.091 # fork operation complete
[2344] 15 Sep 11:50:01.091 \* Background saving terminated with success
[2344] 15 Sep 12:00:04.560 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 12:00:04.576 \* Background saving started by pid 2220
[2344] 15 Sep 12:00:05.029 # fork operation complete
[2344] 15 Sep 12:00:05.029 \* Background saving terminated with success
[2344] 15 Sep 12:00:36.013 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 12:00:36.013 \* Background saving started by pid 2904
[2344] 15 Sep 12:00:36.763 # fork operation complete
[2344] 15 Sep 12:00:36.763 \* Background saving terminated with success
[2344] 15 Sep 12:05:00.560 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 12:05:00.560 \* Background saving started by pid 1648
[2344] 15 Sep 12:05:01.310 # fork operation complete
[2344] 15 Sep 12:05:01.310 \* Background saving terminated with success
[2344] 15 Sep 12:15:27.123 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 12:15:29.826 \* Background saving started by pid 2652
[2344] 15 Sep 12:15:40.513 # fork operation complete
[2344] 15 Sep 12:15:40.732 \* Background saving terminated with success
[2344] 15 Sep 12:20:04.560 \* 5 changes in 30 seconds. Saving...
[2344] 15 Sep 12:20:05.138 \* Background saving started by pid 4856
[4856] 15 Sep 12:20:06.123 #

=== REDIS BUG REPORT START: Cut & paste starting from here ===

2015-09-15 20:27 GMT+03:00 Enrico Giordani notifications@github.com:

> Hi @chester89 https://github.com/chester89,
> it's a memory corruption that seems similar to a problem we have seen in
> the past, can you please post the log before the crash? 50 lines should be
> enough.
> Thank you.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/316#issuecomment-140473269.

## 

Yours faithfully,
Gleb

**Comment by chester89** [comment] 2015-09-20 20:44
Any news on that one @enricogior?

2015-09-15 21:53 GMT+03:00 Gleb Chermennov thebitterend77@gmail.com:

> ​Of course. I don't have the most verbose logging set up, I'm afraid.
> 
> [2344] 15 Sep 10:45:06.154 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 10:45:06.154 \* Background saving started by pid 3216
> [2344] 15 Sep 10:45:07.279 # fork operation complete
> [2344] 15 Sep 10:45:07.279 \* Background saving terminated with success
> [2344] 15 Sep 10:50:00.435 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 10:50:00.435 \* Background saving started by pid 4808
> [2344] 15 Sep 10:50:00.857 # fork operation complete
> [2344] 15 Sep 10:50:00.857 \* Background saving terminated with success
> [2344] 15 Sep 11:00:05.654 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 11:00:05.654 \* Background saving started by pid 4500
> [2344] 15 Sep 11:00:06.294 # fork operation complete
> [2344] 15 Sep 11:00:06.294 \* Background saving terminated with success
> [2344] 15 Sep 11:05:00.529 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 11:05:00.529 \* Background saving started by pid 3248
> [2344] 15 Sep 11:05:01.232 # fork operation complete
> [2344] 15 Sep 11:05:01.232 \* Background saving terminated with success
> [2344] 15 Sep 11:15:05.107 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 11:15:05.107 \* Background saving started by pid 3844
> [2344] 15 Sep 11:15:05.529 # fork operation complete
> [2344] 15 Sep 11:15:05.529 \* Background saving terminated with success
> [2344] 15 Sep 11:20:01.513 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 11:20:01.513 \* Background saving started by pid 2432
> [2344] 15 Sep 11:20:02.263 # fork operation complete
> [2344] 15 Sep 11:20:02.263 \* Background saving terminated with success
> [2344] 15 Sep 11:30:03.951 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 11:30:03.951 \* Background saving started by pid 3176
> [2344] 15 Sep 11:30:05.248 # fork operation complete
> [2344] 15 Sep 11:30:05.248 \* Background saving terminated with success
> [2344] 15 Sep 11:35:00.654 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 11:35:00.654 \* Background saving started by pid 3564
> [2344] 15 Sep 11:35:01.404 # fork operation complete
> [2344] 15 Sep 11:35:01.404 \* Background saving terminated with success
> [2344] 15 Sep 11:40:07.263 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 11:40:07.263 \* Background saving started by pid 3724
> [2344] 15 Sep 11:40:07.810 # fork operation complete
> [2344] 15 Sep 11:40:07.810 \* Background saving terminated with success
> [2344] 15 Sep 11:45:05.138 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 11:45:05.138 \* Background saving started by pid 2820
> [2344] 15 Sep 11:45:05.685 # fork operation complete
> [2344] 15 Sep 11:45:05.685 \* Background saving terminated with success
> [2344] 15 Sep 11:50:00.466 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 11:50:00.466 \* Background saving started by pid 3192
> [2344] 15 Sep 11:50:01.091 # fork operation complete
> [2344] 15 Sep 11:50:01.091 \* Background saving terminated with success
> [2344] 15 Sep 12:00:04.560 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 12:00:04.576 \* Background saving started by pid 2220
> [2344] 15 Sep 12:00:05.029 # fork operation complete
> [2344] 15 Sep 12:00:05.029 \* Background saving terminated with success
> [2344] 15 Sep 12:00:36.013 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 12:00:36.013 \* Background saving started by pid 2904
> [2344] 15 Sep 12:00:36.763 # fork operation complete
> [2344] 15 Sep 12:00:36.763 \* Background saving terminated with success
> [2344] 15 Sep 12:05:00.560 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 12:05:00.560 \* Background saving started by pid 1648
> [2344] 15 Sep 12:05:01.310 # fork operation complete
> [2344] 15 Sep 12:05:01.310 \* Background saving terminated with success
> [2344] 15 Sep 12:15:27.123 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 12:15:29.826 \* Background saving started by pid 2652
> [2344] 15 Sep 12:15:40.513 # fork operation complete
> [2344] 15 Sep 12:15:40.732 \* Background saving terminated with success
> [2344] 15 Sep 12:20:04.560 \* 5 changes in 30 seconds. Saving...
> [2344] 15 Sep 12:20:05.138 \* Background saving started by pid 4856
> [4856] 15 Sep 12:20:06.123 #
> 
> === REDIS BUG REPORT START: Cut & paste starting from here ===
> 
> 2015-09-15 20:27 GMT+03:00 Enrico Giordani notifications@github.com:
> 
> > Hi @chester89 https://github.com/chester89,
> > it's a memory corruption that seems similar to a problem we have seen in
> > the past, can you please post the log before the crash? 50 lines should be
> > enough.
> > Thank you.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MSOpenTech/redis/issues/316#issuecomment-140473269.
> 
> ## 
> 
> Yours faithfully,
> Gleb

## 

Yours faithfully,
Gleb

**Comment by enricogior** [comment] 2015-09-21 08:50
Hi @chester89 
in 2.8.2101 there was a memory corruption that was happening while saving in the background and it has been fixed in the following releases.
I suggest to upgrade.

**Comment by chester89** [comment] 2015-09-21 09:05
Will do, thanks

2015-09-21 11:50 GMT+03:00 Enrico Giordani notifications@github.com:

> Hi @chester89 https://github.com/chester89
> in 2.8.2101 there was a memory corruption that was happening while saving
> in the background and it has been fixed in the following releases.
> I suggest to upgrade.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/316#issuecomment-141913625.

## 

Yours faithfully,
Gleb

**Comment by chester89** [comment] 2015-09-22 19:42
Testing 2.8.2103 now. I noticed something strange - when loading
persistence files (I use both AOF and RDB), I get different loading time
for same files. Did it twice, once it was 4 seconds, later it was less than
1 second. Any ideas?

2015-09-21 12:05 GMT+03:00 Gleb Chermennov thebitterend77@gmail.com:

> Will do, thanks
> 
> 2015-09-21 11:50 GMT+03:00 Enrico Giordani notifications@github.com:
> 
> > Hi @chester89 https://github.com/chester89
> > in 2.8.2101 there was a memory corruption that was happening while saving
> > in the background and it has been fixed in the following releases.
> > I suggest to upgrade.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MSOpenTech/redis/issues/316#issuecomment-141913625.
> 
> ## 
> 
> Yours faithfully,
> Gleb

## 

Yours faithfully,
Gleb

**Comment by enricogior** [comment] 2015-09-25 13:22
@chester89,
it maybe caused by the fact that the second time the file was cached by Windows or maybe the machine had a higher CPU/disk load the first time.

**Comment by chester89** [comment] 2015-09-29 15:31
Running 2103 build for a week now, haven't seen such an error. I guess I
can close this. Thanks

2015-09-25 16:22 GMT+03:00 Enrico Giordani notifications@github.com:

> @chester89 https://github.com/chester89,
> it maybe caused by the fact that the second time the file was cached by
> Windows or maybe the machine had a higher CPU/disk load the first time.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MSOpenTech/redis/issues/316#issuecomment-143219670.

## 

Yours faithfully,
Gleb

**Closed as completed** 2015-09-29 15:32 UTC
