### ISSUE TITLE
crash using slaveof targeting server with persistence-available no

### ISSUE THREAD

**Issue by mattclay** [microsoftarchive/redis#243] opened 2015-05-13 23:10 UTC
Redis-64 version 2.8.19 will crash if you attempt to use it as a master when it is configured without persistence. Reproduction is easy:

1) Run two instances of redis-server with --persistence-available no
2) Issue the slaveof command to point one of the instances at the other

At this point the server being used as the master will crash. The logs on the server prior to the crash show the following:

```
[2604] 13 May 16:00:58.854 # Server started, Redis version 2.8.19
[2604] 13 May 16:00:58.854 * The server is now ready to accept connections on port 6379
[2604] 13 May 16:02:39.511 * Slave x.x.x.x:6379 asks for synchronization
[2604] 13 May 16:02:39.511 * Full resync requested by slave x.x.x.x:6379
[2604] 13 May 16:02:39.511 * Starting BGSAVE for SYNC with target: disk
```

I don't expect replication to work with persistence disabled, but it should return an error instead of crashing the server.

This is related to #212, although that issue makes no mention of a crash.

**Comment by orangemocha** [comment] 2015-05-15 13:41
Thanks for your report, @mattclay . This is indeed the same issue tracked at https://github.com/MSOpenTech/redis/issues/212. The server will crash. While this scenario is not supposed to work, Redis should give a better error message either at startup time or when the slave attempts to connect.

Closing as duplicate of https://github.com/MSOpenTech/redis/issues/212

**Closed as completed by orangemocha** 2015-05-15 13:41 UTC
