### ISSUE TITLE
RedisPanic BGREWRITEAOF

### ISSUE THREAD

**Issue by brainstormi** [microsoftarchive/redis#65] opened 2013-10-09 23:26 UTC
It seems that BGREWRITEAOF is not stable in the current branch (2.6). In my tests, 
with only a bit more than 10000 keys in memory, if BGREWRITEAOF is invoked while a write 
pipeline operation againts a HashSet of about 80000 writes (flushing each 10000 write ops.), 
in the best case RedisServer.exe crash with a RedisPanic error...
        In the worst case, and unfortunatly the usual one, RedisServer directly hangs without 
notifying further information, any client connected to it also hungs trying to connect to the server. 
Also if you try to connect directly with redis-cli, it hungs waiting in a infinite loop without errors 
of any kind.
        In this last scenario, if you enable logverbose to debug level, you could see that suddenly 
RedisServer stops any logging activity when this happens, without further notications or erros.
        I was able to reproduce this scenario almost consistently, with only 2 clients connected to 
the server, one executing the write pipeline command, meanwhile BGREWRITEAOF command is 
launched in a redis-cli session, once we already started to pipeline write commands.
       Original appendfile was around 100MB... if launched BGREWRITEAOF, without any further 
REDIS activity, it consolidates succesfully in only 11MB file. Pipeline write command in these tests,
is always the same and it only crash RedisServer if BGREWRITEAOF is invoked in the middle of the
pipeline operation.
Regards,

**Comment by jepickett** [comment] 2013-10-18 22:35
Thank you for reporting this. This will be looked at before we release 2.6.14.

**Comment by tekr** [comment] 2014-02-09 08:47
Has this been resolved in the 2.6.14 branch?

**Comment by jepickett** [comment] 2014-02-12 18:14
This is likely fixed in 2,6.14. We have moved to a new fork() mechanism that has eliminated all of the background AOF and RDB crashes that we were able to replicate. 2.6.14 is going through a test pass at the moment. We should have an official announcement of its availability soon.

**Comment by jepickett** [comment] 2014-04-02 00:43
2.6.14 and 2.8.4 have been released. The signed binaries are available from NuGet and Chocolatey. The hangs were caused by the previous method of working around the UNIX fork() API. The new code works much better.

**Closed as completed** 2014-04-16 01:17 UTC
Labels: Bug
